### PR TITLE
Mean clim obs info dict update

### PR DESCRIPTION
**Pull request by lee1043**

### CODE REVIEW

**Review by acordonez — COMMENTED** [review]
I tried a test run with hfss, hus, and hur. The hfss part worked for all regions, but I'm getting the following error for hus and hur, with all regions:

INFO::2022-10-19 11:16::pcmdi_metrics::E3SM:: VAR: hus, REGION: global
INFO::2022-10-19 11:16::pcmdi_metrics::E3SM:: reference_data_set (given): ['all'], reference_data_set_is_obs: True, test_data_set_is_obs: False
INFO::2022-10-19 11:16::pcmdi_metrics::E3SM:: reference_data_set (adjusted): ['default'], test_data_set: ['E3SM-1-0']
INFO::2022-10-19 11:16::pcmdi_metrics::E3SM:: default is an obs
INFO::2022-10-19 11:16::pcmdi_metrics::E3SM:: Could not figure out obs mask name from obs json file
INFO::2022-10-19 11:16::pcmdi_metrics::E3SM:: TEST DATA IS: E3SM-1-0
INFO::2022-10-19 11:16::pcmdi_metrics::E3SM:: E3SM-1-0 is a model
INFO::2022-10-19 11:16::pcmdi_metrics::E3SM:: Unexpected error in calculate output metrics: Only length-1 arrays can be converted to Python scalars

**Comment by lee1043** [comment]
@acordonez I think I've got some clue. The error message for `hus` and `hur` is caused by treating them like spatial 2d variable, while they actually are spatial 3d variables with level. 

I tested `hus_850` and `hur_850` and they worked for me. Can you try that on your end and see if that works for you?

**Comment by acordonez** [comment]
@lee1043 Yes that worked for me! Thank you.

**Review by acordonez — APPROVED** [review]

**Comment by lee1043** [comment]
@acordonez Excellent, thank you for checking on that.

**Pull request merged**
