### PR TITLE
Wang xcdat clean

### PR DESCRIPTION
**Pull request by bosup**
converted to xcdat

### CODE REVIEW

**Comment by lee1043** [comment]
@bosup It looks like all the output netcdf files were added to this PR, which might have caused by `git add .` Can you exclude them from the PR?

**Comment by lee1043** [comment]
@bosup I also see files changed under monsoon_sperber directory, which is confusing as this PR is mostly for monsoon Wang. Can you double check on that?

**Comment by lee1043** [comment]
For the output files, we are archiving them in separate. JSONs can be saved to https://github.com/PCMDI/pcmdi_metrics_results_archive. Both netcdf and JSON files also can be placed in the certain directory in gates. I can point those directories to you via email.

**Comment by bosup** [comment]
> @bosup It looks like all the output netcdf files were added to this PR, which might have caused by `git add .` Can you exclude them from the PR?

I unstaged those output files and re added .py files now

**Comment by bosup** [comment]
> For the output files, we are archiving them in separate. JSONs can be saved to https://github.com/PCMDI/pcmdi_metrics_results_archive. Both netcdf and JSON files also can be placed in the certain directory in gates. I can point those directories to you via email.

Thanks for sharing this info! Good to know we have such a data archive.

**Comment by lee1043** [comment]
> > @bosup It looks like all the output netcdf files were added to this PR, which might have caused by `git add .` Can you exclude them from the PR?
> 
> I unstaged those output files and re added .py files now

At the top of this PR page, there is a tab named as "files", and it shows list of changed/staged files for this PR (see [here](https://github.com/PCMDI/pcmdi_metrics/pull/1198/files)). It indicates there still are 317 files staged for this PR, which I don't think monsoon wang metrics have that many files.

**Comment by lee1043** [comment]
You might also need to rebase your branch (sync latest version of the main branch with your branch, which should be done by resolving the conflicts. 
Screenshot 2024-11-25 at 2 58 31 PM

**Comment by bosup** [comment]
> > > @bosup It looks like all the output netcdf files were added to this PR, which might have caused by `git add .` Can you exclude them from the PR?
> > 
> > 
> > I unstaged those output files and re added .py files now
> 
> At the top of this PR page, there is a tab named as "files", and it shows list of changed/staged files for this PR (see [here](https://github.com/PCMDI/pcmdi_metrics/pull/1198/files)). It indicates there still are 317 files staged for this PR, which I don't think monsoon wang metrics have that many files.

Got it! output .nc and .png files are removed, leaving 15 file changed now.

**Comment by lee1043** [comment]
I am closing this PR as it is followed up by #1200.

**Pull request closed without merging**
