### PR TITLE
Fixed issue where nox was uploading non-nox code

### PR DESCRIPTION
**Pull request by zshaheen**

### CODE REVIEW

**Comment by durack1** [comment]
@zshaheen it seems that going through the motions of a `v1.1.1-nox` uncovered an issue?

**Comment by zshaheen** [comment]
@durack1 Yup. v1.1.1 nox is up for osx. The linux version on Anaconda should be up soon.

**Comment by durack1** [comment]
@zshaheen perfect, `linux` is what I was chasing for GFDL.. I'll check back a bit later today

**Comment by zshaheen** [comment]
@durack1 Okay, we're good. See here:

https://anaconda.org/PCMDI/pcmdi_metrics-nox/files?version=v1.1.1

Let me know if there are any problems.

**Comment by durack1** [comment]
@zshaheen you're an absolute hero.. I'll give that ago on their systems.. THANKS!

**Comment by durack1** [comment]
@zshaheen it all works fine.. I've now got to sort out the json formatting changes, so I am feeding the plotting routine some real numbers.. Thanks again

**Comment by zshaheen** [comment]
@durack1 No problem. That's great to hear.

**Pull request merged**
