### PR TITLE
Remove ymal files to start from scratch

### PR DESCRIPTION
**Pull request by lee1043**

### CODE REVIEW

**Comment by acordonez** [comment]
@lee1043 had another thought - do we need the Makefile anymore if .circleci is gone?

**Comment by lee1043** [comment]
@acordonez Great point. I do not have good understanding of purpose of the Makefile. If it is certain that the Makefile has been only used with circle ci, I agree we can remove it. Do you know how Makefile have been used in the workflow?

**Comment by acordonez** [comment]
@lee1043  I searched for each of the targets in the Makefile (e.g. conda-rerender) in the repo and many of them don't show up outside the Makefile. The ones that do only show up in .circleci/config.yml. The CircleCI config also looks like the only place we use "make" commands in the repo. Based on that info, it looks like the Makefile is only used for the CircleCI workflows.

**Comment by lee1043** [comment]
@acordonez thanks for investigating. In this PR, I removed circle ci related files and added github action workflow initiative. I agree it may be easier if we merge this to master before we ask Tom and Jason to step in. I will merge it when you approve the changes.

**Comment by acordonez** [comment]
@lee1043 I don't see anything else that looks like it should be deleted.

**Review by acordonez — APPROVED** [review]
LGTM

**Pull request merged**
