### PR TITLE
All Contributors

### PR DESCRIPTION
**Pull request by lee1043**
Apply [All Contributors](https://allcontributors.org/) following their [instruction](https://allcontributors.org/docs/en/bot/installation) to recognize all contributors in the README file.

### CODE REVIEW

**Comment by lee1043** [comment]
@all-contributors generate

**Comment by lee1043** [comment]
@all-contributors add @lee1043 <dev>

**Comment by lee1043** [comment]
https://github.com/all-contributors add @lee1043 code

**Comment by lee1043** [comment]
@all-contributors please add @lee1043 for code

**Comment by lee1043** [comment]
@all-contributors please add @lee1043 @gleckler1 @doutriaux1 @msahn @acordonez @durack1 @mzelinka @zshaheen @mauzey1 @tomvothecoder @jasonb5 @painter1 @xylar @jkrasting for code

**Comment by lee1043** [comment]
Updated README with new contributor list will look like [this](https://github.com/PCMDI/pcmdi_metrics/blob/fec2720730a4c9d13f83d0f02e7f9756530b1829/README.md#contributors).

**Comment by lee1043** [comment]
Updated README: https://github.com/PCMDI/pcmdi_metrics/tree/all-contributor

**Review by acordonez — APPROVED** [review]
This looks great Jiwoo!

**Comment by tomvothecoder** [comment]
This is a cool repo extension. Thanks for the recognition Jiwoo!

**Pull request merged**
