### PR TITLE
Summary visualization: portrait and parallel coordinate plots

### PR DESCRIPTION
**Pull request by lee1043**

### CODE REVIEW

**Comment by lee1043** [comment]
To do's:
- [ ] Add PMP logo on portrait plot
- [ ] [Discrete colormap](https://matplotlib.org/stable/tutorials/colors/colorbar_only.html) option

**Comment by lee1043** [comment]
Additional to do's:
- [ ] Further simplify read json function
- [ ] fig ratio coordinate for portrait plot legend

**Comment by acordonez** [comment]
@lee1043  Are there particular jupyter notebooks or scripts I should try running?

**Comment by lee1043** [comment]
@acordonez thanks for checking. In readme files for [portrait plot](https://github.com/PCMDI/pcmdi_metrics/tree/756_ljw_visualization/pcmdi_metrics/graphics/portrait_plot) and [parallel coordinate plot](https://github.com/PCMDI/pcmdi_metrics/tree/756_ljw_visualization/pcmdi_metrics/graphics/parallel_coordinate_plot), there are two jupyter notebooks in each readme: one for example and another for use case (mean clim). Could you please check if those notebooks run well on your end?

**Review by acordonez — APPROVED** [review]
I tested the 4 jupyter notebooks and they are all working for me now. LGTM!

**Pull request merged**
