### PR TITLE
Revert "Added rmsc_xyt.py and modified mean_climate_metrics_calculations.py"

### PR DESCRIPTION
**Pull request by doutriaux1**
Reverts PCMDI/pcmdi_metrics#471

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 that's already done!

**Comment by durack1** [comment]
#474

**Comment by jservonnat** [comment]
Did you guys eventually merged the modifications?

**Comment by doutriaux1** [comment]
Apprarently yes because it says 0 file changed.

**Pull request closed without merging**
