### PR TITLE
Cia unify part one

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@gleckler1 @durack1 it's now using CIA for monsoon and dirunal

But in order for this to pass we need to reslove: https://github.com/PCMDI/pcmdi_metrics/pull/527

**Comment by gleckler1** [comment]
@doutriaux1   The big leap is getting monsoon and dirunal working with CIA using a parameter file.   It looks like these changes are just for the command line (argparse) path.   Is that correct?

**Comment by durack1** [comment]
@doutriaux1 not sure I'm going to get to run this to thoroughly check - is the test suite testing this new code?

**Comment by doutriaux1** [comment]
@gleckler1 they should work with a parameter file. I'll check.

**Comment by gleckler1** [comment]
@doutriaux1   Need to get this to work.   Now setup.py won't run on branch origin/cia_unify_part_one.   looks like a py3 issue...

I've been trying to create an env (below) with pcmdi_metrics and cia and a parameter file... I've blown 1/2 so far, still can't do it...

conda create -n pmp_mar21 -c uvcdat/label/nightly -c conda-forge -c uvcdat -c pcmdi/label/nightly -c pcmdi vcs vcsaddons pcmdi_metrics cia

**Comment by doutriaux1** [comment]
@gleckler1 let's look in the morning

**Pull request merged**
