### PR TITLE
Use updated conda recipes

### PR DESCRIPTION
**Pull request by muryanto1**
add Makefile and use 'master' branch of cdat/cdat since 'validateNightlyNew' branch has been merged to 'master'.

### CODE REVIEW

**Comment by muryanto1** [comment]
@lee1043 https://circleci.com/gh/PCMDI  all test runs passed. those circleci job like linux_pmp_* macos_pmp_* jobs that are listed above that still say "Required" are old circleci jobs.  
The build above picked up the genutil that has @jasonb5 's fix for https://github.com/CDAT/genutil/issues/38.
NOTE that I added py36, py37, py38 for both macos and linux.  As a result, each commit triggers builds and test runs that take a long time to finish. It is up to you if you want to include all those configs.

**Comment by lee1043** [comment]
@muryanto1 thank you for the update. Once all tests passes on circle ci, which is pending now, I will merge this.

**Comment by muryanto1** [comment]
@lee1043 all tests passed, please see the list of tests under "Some checks haven't completed yet".  build-linux, build-macos, test-linux-3.6-mpi_mpich, test-linux-3.6-mpi_openmpi, test-linux-3.6-nompi, etc...they are all jobs from .circleci/config.yml, and they all passed. For some reason the old jobs linux_pmp_py2, linux_pmp_py3 and macos_pmp_py2, macos_pmp_py3 are still listed up there under "Some checks haven't completed yet". I do not know why.

**Comment by lee1043** [comment]
@muryanto1 I see, thanks for clarifying. Because of the "Some checks haven't completed yet" showing up, I thought it was still processing. I am merging it now.

**Pull request merged**
