### PR TITLE
Simplify demo 9b

### PR DESCRIPTION
**Pull request by lee1043**
Demo 9b is simplified by removing the interactive visualization part.

### CODE REVIEW

**Comment by lee1043** [comment]
I removed the interactive visualization part considering time limit, and also some of them was not working properly on Nimbus binder hub.

**Review by durack1 — APPROVED** [review]
@lee1043 a quick diff glance looks like this has simplified things a lot!

**Review by acordonez — APPROVED** [review]
Everything in this version worked for me on gates and Nimbus.

**Comment by lee1043** [comment]
@acordonez @durack1 thanks for checking!

**Pull request merged**
