### PR TITLE
Jupyter notebook for climatology script

### PR DESCRIPTION
**Pull request by acordonez**
This PR pulls the annual cycle demo from the mean climate notebook (Demo 1) and moves it to its own notebook (Demo 1a).

### CODE REVIEW

**Comment by gleckler1** [comment]
@acordonez not sure what has happened here - perhaps it is out of sync with the PR that was merged earlier this AM?

**Comment by acordonez** [comment]
@gleckler1 That could be it - I relaunched the tests in CircleCI and they're doing fine now. Is there a way to rerun them for the PR, or should I try closing and reopening it?

**Comment by gleckler1** [comment]
@acordonez hmm... I don't know the answer to that one

**Comment by acordonez** [comment]
@gleckler1 I was able to pull in some changes from master and do another push to trigger the tests again.

**Pull request merged**
