### PR TITLE
Py3

### PR DESCRIPTION
**Pull request by doutriaux1**
All done. Py3 fails because it runs with esmf 7.1 which is different form 7.0 (py2 fails both from master or this with esmf 7.1)

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 time for a new baseline with ESMF7.1 (if we get comparable results using `regrid2` for the atmos grids)

@gleckler1

**Comment by doutriaux1** [comment]
@gleckler1 thiking of switching the tests to use linear at least until https://github.com/UV-CDAT/cdms/issues/231 is fixed. What do you think?

**Comment by doutriaux1** [comment]
@durack1 agreed, that's why we could also disable conservative completely at the moment and raise an error, until this bug is addressed. Thoughts?

**Comment by durack1** [comment]
@doutriaux1 this is not released, right? A warning would be a good idea until the behaviour is acceptable

**Comment by gleckler1** [comment]
@doutriaux1 @dnadeau4 @durack1   Seems like a good thing to do if not too onerous.  I have told the E3SM people using the PMP to not use ESMF conservative until we resolve this, but maybe better is to disable for now.

**Comment by doutriaux1** [comment]
ok will disable on Monday and merge this in master.

**Pull request merged**
