### PR TITLE
adding ESGF2-US logos; suggested text tweaks

### PR DESCRIPTION
**Pull request by durack1**
@lee1043 @acordonez adding the ESGF2-US logos to both notebooks and some suggested tweaks for the secondary/supplementary notebook

### CODE REVIEW

**Review by lee1043 — APPROVED** [review]
@durack1 Thank you for the tweak!

**Comment by durack1** [comment]
@lee1043 whoops, I should have tagged this "draft".. Still have to check logo sizes in the second notebook - I was trying to size things similarly, which meant upping the PCMDI size to 100px width

**Comment by durack1** [comment]
@lee1043 looks like the resizing messed things up a bit!
Screenshot 2024-01-30 at 6 06 18 PM

**Comment by lee1043** [comment]
@durack1 sorry, I thought it was ready. I restored the branch and please feel free to continue working on that branch and let me know when it is ready.

**Comment by lee1043** [comment]
Screenshot 2024-01-30 at 9 27 15 PM

It looks okay on my end. I will delete the branch, but please feel free to reopen it if the issue still remain on your end.

**Comment by lee1043** [comment]
The issue fixed by #1038 and the change merged to the main.

**Comment by durack1** [comment]
@lee1043 yep this looks good to me now in main - using the nbviewer parsed versions
Screenshot 2024-01-31 at 5 43 44 AM

**Pull request merged**
