### PR TITLE
Extremes Metrics

### PR DESCRIPTION
**Pull request by acordonez**
Extremes Metrics

See the [README](https://github.com/PCMDI/pcmdi_metrics/blob/534_ao_extremes/pcmdi_metrics/extremes/README.md) for more details.

The Github.io documentation will be updated in a second PR (#990). 

This PR contains:
The extremes driver and library code
Jupyter notebook demo

The demo ([Notebook #8](https://github.com/PCMDI/pcmdi_metrics/blob/534_ao_extremes/doc/jupyter/Demo/Demo_8_extremes.ipynb)) uses precipitation data that is already distributed as part of the demo data bundle, but processes it to make a lower resolution version that runs much more quickly. At the original resolution, it takes me around an hour to run each example.

Dependency note: This code also requires adding the "numdifftools" package as a dependency (this is available on conda-forge).

### CODE REVIEW

**Comment by lee1043** [comment]
Thank you for the PR!  I edited your note to point demo notebook to below link (instead of automatically linking to issue 8):
https://github.com/PCMDI/pcmdi_metrics/blob/534_ao_extremes/doc/jupyter/Demo/Demo_8_extremes.ipynb

**Comment by acordonez** [comment]
Summary edited to add note about numdifftools

**Comment by lee1043** [comment]
@acordonez thank you for the PR, and sorry that it took a while for me to start reviewing this PR. 

It looks like numdifftools is a new dependency needed for extreme, which I added to dev.yml. 

From the Demo8 notebook, I am getting following error.

```
extremes_driver.py  -p basic_extremes_param.py
```

```
# Settings for extremes driver

# These settings are required
vars = ['pr'] # Choices are 'pr','tasmax', 'tasmin'
test_data_set = ['GISS-E2-H']
realization = ['r6i1p1']
test_data_path = 'demo_output/extremes_tmp/'
filename_template = '%(variable)_day_%(model)_historical_%(realization)_20000101-20051231.nc'
metrics_output_path = 'demo_output/%(case_id)'

# Note: You can use the following placeholders in file templates:
# %(variable) to substitute variable name from "vars" (except in sftlf filenames)
# %(model) to substitute model name from "test_data_set"
# %(realization) to substitute realization from "realization"

# Optional settings
# See the README for more information about these settings
case_id = 'extremes_ex1'
#sftlf_filename_template = 'demo_data/CMIP5_demo_data/cmip5.historical.%(model).sftlf.nc'

ModUnitsAdjust = (True,'multiply',86400.,'mm/day') # Convert model units from kg/m2/s to mm/day
ObsUnitsAdjust = (True,'multiply',86400.,'mm/day') # Convert obs units
dec_mode='JFD'
annual_strict = True
drop_incomplete_djf = True
...
plots=False
generate_sftlf = True
return_period = 2

Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?7861abe4-f2e9-4f4a-a20f-518ac377caac) or open in a [text editor](command:workbench.action.openLargeOutput?7861abe4-f2e9-4f4a-a20f-518ac377caac). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
No sftlf file found for GISS-E2-H r6i1p1

-----------------------
model, run, variable: GISS-E2-H r6i1p1 pr
test_data (model in this case) full_path:
   demo_output/extremes_tmp/pr_day_GISS-E2-H_historical_r6i1p1_20000101-20051231.nc
Generating land sea mask.
Generating precipitation block extrema.
Traceback (most recent call last):
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20230223/bin/extremes_driver.py", line 386, in <module>
    Rx1day, Rx5day = compute_metrics.precipitation_indices(
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20230223/lib/python3.9/site-packages/pcmdi_metrics/extremes/lib/compute_metrics.py", line 404, in precipitation_indices
    P1day = update_nc_attrs(P1day, dec_mode, drop_incomplete_djf, annual_strict)
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20230223/lib/python3.9/site-packages/pcmdi_metrics/extremes/lib/compute_metrics.py", line 287, in update_nc_attrs
    ds = ds.bounds.add_missing_bounds()
TypeError: add_missing_bounds() missing 1 required positional argument: 'axes'
```

I think this error is coming from [this line](https://github.com/PCMDI/pcmdi_metrics/blob/89af0615fcd134c247d2013cf091b63497fbea29/pcmdi_metrics/extremes/lib/compute_metrics.py#L287), `ds = ds.bounds.add_missing_bounds()`. 

In the latest xcdat version, `add_missing_bounds` function requires parameters ([doc](https://xcdat.readthedocs.io/en/latest/generated/xarray.Dataset.bounds.add_missing_bounds.html)). 

@tomvothecoder do you have any advice?

**Comment by acordonez** [comment]
@lee1043  Thanks for updating dev.yml. 

With regards to the add_missing_bounds call, I can manually loop through the lat, lon, and time bounds to check which ones are present. Whether they are there depends on what's in the input dataset, which might not have all the bounds.

**Comment by lee1043** [comment]
@acordonez Regarding the add_missing_bounds operation I think that manual loop would be good workaround. During the meantime, I also opened an issue on xcdat board: https://github.com/xCDAT/xcdat/issues/563

**Comment by tomvothecoder** [comment]
> I think this error is coming from [this line](https://github.com/PCMDI/pcmdi_metrics/blob/89af0615fcd134c247d2013cf091b63497fbea29/pcmdi_metrics/extremes/lib/compute_metrics.py#L287), `ds = ds.bounds.add_missing_bounds()`.
> 
> In the latest xcdat version, `add_missing_bounds` function requires parameters ([doc](https://xcdat.readthedocs.io/en/latest/generated/xarray.Dataset.bounds.add_missing_bounds.html)).
> 
> @tomvothecoder do you have any advice?

My response here: https://github.com/xCDAT/xcdat/issues/563#issuecomment-1806542734

**Comment by acordonez** [comment]
@lee1043 This PR (https://github.com/xCDAT/xcdat/pull/569) should fix the issue with the call to add_missing_bounds().

**Comment by lee1043** [comment]
@acordonez thank you for working on the xCDAT PR! Once the PR merged to the xCDAT main, I will test with its latest version.

**Comment by acordonez** [comment]
@lee1043 I should have mentioned that the PR has been merged already, so it should be available for dev use.

**Comment by lee1043** [comment]
@acordonez it looks like the error is coming from not having a calendar attribute in the input data for the [test suite](https://github.com/PCMDI/pcmdi_metrics/blob/02a8ec86e23e3f5064c991ee3b1891c54da9ea4b/tests/test_extremes.py#L75). 

```
=========================== short test summary info ============================
FAILED tests/test_extremes.py::test_seasonal_averager_settings - KeyError: 'calendar'
FAILED tests/test_extremes.py::test_seasonal_averager_ann_max - KeyError: 'calendar'
FAILED tests/test_extremes.py::test_seasonal_averager_ann_min - KeyError: 'calendar'
FAILED tests/test_extremes.py::test_seasonal_averager_ann_djf - KeyError: 'calendar'
FAILED tests/test_extremes.py::test_seasonal_averager_rolling_mam - KeyError: 'calendar'
FAILED tests/test_extremes.py::test_seasonal_averager_rolling_djf - KeyError: 'calendar'
=================== 6 failed, 3 passed, 7 warnings in 15.23s ===================
```

**Comment by lee1043** [comment]
@acordonez I am getting a new error from Demo8 notebook's `extremes_driver.py  -p basic_extremes_param.py`. Does it look familiar to you?

```
# Settings for extremes driver

# These settings are required
vars = ['pr'] # Choices are 'pr','tasmax', 'tasmin'
test_data_set = ['GISS-E2-H']
realization = ['r6i1p1']
test_data_path = 'demo_output/extremes_tmp/'
filename_template = '%(variable)_day_%(model)_historical_%(realization)_20000101-20051231.nc'
metrics_output_path = 'demo_output/%(case_id)'

# Note: You can use the following placeholders in file templates:
# %(variable) to substitute variable name from "vars" (except in sftlf filenames)
# %(model) to substitute model name from "test_data_set"
# %(realization) to substitute realization from "realization"

# Optional settings
# See the README for more information about these settings
case_id = 'extremes_ex1'
#sftlf_filename_template = 'demo_data/CMIP5_demo_data/cmip5.historical.%(model).sftlf.nc'

ModUnitsAdjust = (True,'multiply',86400.,'mm/day') # Convert model units from kg/m2/s to mm/day
ObsUnitsAdjust = (True,'multiply',86400.,'mm/day') # Convert obs units
dec_mode='JFD'
annual_strict = True
drop_incomplete_djf = True
...
plots=False
generate_sftlf = True
return_period = 2

Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?1d50ce80-e393-4aca-8b4b-250cfd4670fe) or open in a [text editor](command:workbench.action.openLargeOutput?1d50ce80-e393-4aca-8b4b-250cfd4670fe). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
No sftlf file found for GISS-E2-H r6i1p1

-----------------------
model, run, variable: GISS-E2-H r6i1p1 pr
test_data (model in this case) full_path:
   demo_output/extremes_tmp/pr_day_GISS-E2-H_historical_r6i1p1_20000101-20051231.nc
Generating land sea mask.
Generating precipitation block extrema.
Writing results to netCDF.
Generating metrics.
INFO::2023-12-22 13:00::pcmdi_metrics:: Results saved to a json file: [/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/GISS-E2-H_block_extremes_metrics.json](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/GISS-E2-H_block_extremes_metrics.json)
2023-12-22 13:00:39,824 [INFO]: base.py(write:251) >> Results saved to a json file: [/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/GISS-E2-H_block_extremes_metrics.json](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/GISS-E2-H_block_extremes_metrics.json)
2023-12-22 13:00:39,824 [INFO]: base.py(write:251) >> Results saved to a json file: [/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/GISS-E2-H_block_extremes_metrics.json](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/GISS-E2-H_block_extremes_metrics.json)
INFO::2023-12-22 13:00::pcmdi_metrics:: Results saved to a json file: [/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/block_extremes_metrics.json](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/block_extremes_metrics.json)
2023-12-22 13:00:56,588 [INFO]: base.py(write:251) >> Results saved to a json file: [/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/block_extremes_metrics.json](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/block_extremes_metrics.json)
2023-12-22 13:00:56,588 [INFO]: base.py(write:251) >> Results saved to a json file: [/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/block_extremes_metrics.json](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/block_extremes_metrics.json)
Generating return values.
demo_output/extremes_ex1/netcdf/GISS-E2-H_r6i1p1_land_Rx5day_2000-2005.nc
Return value for single realization
Stationary case
[/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/return_value.py:288](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/return_value.py:288): RuntimeWarning: Mean of empty slice
  scale_factor = np.abs(np.nanmean(data))
demo_output/extremes_ex1/netcdf/GISS-E2-H_r6i1p1_land_Rx1day_2000-2005.nc
Return value for single realization
Stationary case
[/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/return_value.py:288](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/return_value.py:288): RuntimeWarning: Mean of empty slice
  scale_factor = np.abs(np.nanmean(data))
2023-12-22 13:00:57,246 [WARNING]: dataset.py(open_dataset:128) >> "No time coordinates were found in this dataset to decode. If time coordinates were expected to exist, make sure they are detectable by setting the CF 'axis' or 'standard_name' attribute (e.g., ds['time'].attrs['axis'] = 'T' or ds['time'].attrs['standard_name'] = 'time'). Afterwards, try decoding again with `xcdat.decode_time`."
2023-12-22 13:00:57,246 [WARNING]: dataset.py(open_dataset:128) >> "No time coordinates were found in this dataset to decode. If time coordinates were expected to exist, make sure they are detectable by setting the CF 'axis' or 'standard_name' attribute (e.g., ds['time'].attrs['axis'] = 'T' or ds['time'].attrs['standard_name'] = 'time'). Afterwards, try decoding again with `xcdat.decode_time`."
Traceback (most recent call last):
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/bin/extremes_driver.py", line 607, in <module>
    tmp = compute_metrics.metrics_json_return_value(
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/compute_metrics.py", line 638, in metrics_json_return_value
    obs = obs.bounds.add_missing_bounds()
AttributeError: 'NoneType' object has no attribute 'bounds'
```

**Comment by acordonez** [comment]
@lee1043 I think I know what's causing that message, I should be able to fix it pretty quickly.

**Comment by acordonez** [comment]
> @acordonez I am getting a new error from Demo8 notebook's `extremes_driver.py -p basic_extremes_param.py`. Does it look familiar to you? (Below log message is updated)
> 
> ```
> No sftlf file found for GISS-E2-H r6i1p1
> 
> -----------------------
> model, run, variable: GISS-E2-H r6i1p1 pr
> test_data (model in this case) full_path:
>    demo_output/extremes_tmp/pr_day_GISS-E2-H_historical_r6i1p1_20000101-20051231.nc
> Generating land sea mask.
> Generating precipitation block extrema.
> Writing results to netCDF.
> Generating metrics.
> INFO::2023-12-22 13:00::pcmdi_metrics:: Results saved to a json file: [/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/GISS-E2-H_block_extremes_metrics.json](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/GISS-E2-H_block_extremes_metrics.json)
> 2023-12-22 13:00:39,824 [INFO]: base.py(write:251) >> Results saved to a json file: [/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/GISS-E2-H_block_extremes_metrics.json](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/GISS-E2-H_block_extremes_metrics.json)
> 2023-12-22 13:00:39,824 [INFO]: base.py(write:251) >> Results saved to a json file: [/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/GISS-E2-H_block_extremes_metrics.json](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/GISS-E2-H_block_extremes_metrics.json)
> INFO::2023-12-22 13:00::pcmdi_metrics:: Results saved to a json file: [/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/block_extremes_metrics.json](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/block_extremes_metrics.json)
> 2023-12-22 13:00:56,588 [INFO]: base.py(write:251) >> Results saved to a json file: [/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/block_extremes_metrics.json](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/block_extremes_metrics.json)
> 2023-12-22 13:00:56,588 [INFO]: base.py(write:251) >> Results saved to a json file: [/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/block_extremes_metrics.json](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/git/pcmdi_metrics_20230620_pcmdi/pcmdi_metrics/doc/jupyter/Demo/demo_output/extremes_ex1/block_extremes_metrics.json)
> Generating return values.
> demo_output/extremes_ex1/netcdf/GISS-E2-H_r6i1p1_land_Rx5day_2000-2005.nc
> Return value for single realization
> Stationary case
> [/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/return_value.py:288](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/return_value.py:288): RuntimeWarning: Mean of empty slice
>   scale_factor = np.abs(np.nanmean(data))
> demo_output/extremes_ex1/netcdf/GISS-E2-H_r6i1p1_land_Rx1day_2000-2005.nc
> Return value for single realization
> Stationary case
> [/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/return_value.py:288](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/return_value.py:288): RuntimeWarning: Mean of empty slice
>   scale_factor = np.abs(np.nanmean(data))
> 2023-12-22 13:00:57,246 [WARNING]: dataset.py(open_dataset:128) >> "No time coordinates were found in this dataset to decode. If time coordinates were expected to exist, make sure they are detectable by setting the CF 'axis' or 'standard_name' attribute (e.g., ds['time'].attrs['axis'] = 'T' or ds['time'].attrs['standard_name'] = 'time'). Afterwards, try decoding again with `xcdat.decode_time`."
> 2023-12-22 13:00:57,246 [WARNING]: dataset.py(open_dataset:128) >> "No time coordinates were found in this dataset to decode. If time coordinates were expected to exist, make sure they are detectable by setting the CF 'axis' or 'standard_name' attribute (e.g., ds['time'].attrs['axis'] = 'T' or ds['time'].attrs['standard_name'] = 'time'). Afterwards, try decoding again with `xcdat.decode_time`."
> Traceback (most recent call last):
>   File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/bin/extremes_driver.py", line 607, in <module>
>     tmp = compute_metrics.metrics_json_return_value(
>   File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/compute_metrics.py", line 638, in metrics_json_return_value
>     obs = obs.bounds.add_missing_bounds()
> AttributeError: 'NoneType' object has no attribute 'bounds'
> ```

@lee1043 I think the new push should fix this error

**Comment by lee1043** [comment]
@acordonez thank you for the fix, it resolved the error. However there is a new error as below, do you have an idea?
```
%%bash
extremes_driver.py  -p basic_extremes_param.py \
--case_id extremes_ex2 \
--reference_data_path demo_output/extremes_tmp/pr_day_GPCP-1-3_PCMDI_gn_19961002-20170101.nc  \
--reference_data_set GPCP-1-3 \
--generate_sftlf \
--regrid True
```

```
Metrics output path not found.
Creating metrics output directory demo_output/extremes_ex2
No reference sftlf file template provided.

-----------------------
model, run, variable: Reference GPCP-1-3 pr
test_data (model in this case) full_path:
   demo_output/extremes_tmp/pr_day_GPCP-1-3_PCMDI_gn_19961002-20170101.nc
Generating land sea mask.
Generating precipitation block extrema.
Writing results to netCDF.
No sftlf file found for GISS-E2-H r6i1p1

-----------------------
model, run, variable: GISS-E2-H r6i1p1 pr
test_data (model in this case) full_path:
   demo_output/extremes_tmp/pr_day_GISS-E2-H_historical_r6i1p1_20000101-20051231.nc
Generating land sea mask.
Generating precipitation block extrema.
Writing results to netCDF.
Generating metrics.
Traceback (most recent call last):
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/bin/extremes_driver.py", line 458, in <module>
    result_dict = compute_metrics.metrics_json(
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/compute_metrics.py", line 565, in metrics_json
    obs_m = obs_dict[m].regridder.horizontal(
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/xcdat/regridder/accessor.py", line 323, in horizontal
    regridder = regrid_tool(input_grid, output_grid, **options)
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/xcdat/regridder/regrid2.py", line 52, in __init__
    self._dst_lat = self._output_grid.bounds.get_bounds("Y")
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/xcdat/bounds.py", line 247, in get_bounds
    raise KeyError(
KeyError: "No bounds data variables were found for the 'Y' axis. Make sure the dataset has bound data vars and their names match the 'bounds' attributes found on their related time coordinate variables. Alternatively, you can add bounds with `ds.bounds.add_missing_bounds()` or `ds.bounds.add_bounds()`."
```

**Comment by acordonez** [comment]
> @acordonez thank you for the fix, it resolved the error. However there is a new error as below, do you have an idea?
> 
> ```
> %%bash
> extremes_driver.py  -p basic_extremes_param.py \
> --case_id extremes_ex2 \
> --reference_data_path demo_output/extremes_tmp/pr_day_GPCP-1-3_PCMDI_gn_19961002-20170101.nc  \
> --reference_data_set GPCP-1-3 \
> --generate_sftlf \
> --regrid True
> ```
> 
> ```
> Metrics output path not found.
> Creating metrics output directory demo_output/extremes_ex2
> No reference sftlf file template provided.
> 
> -----------------------
> model, run, variable: Reference GPCP-1-3 pr
> test_data (model in this case) full_path:
>    demo_output/extremes_tmp/pr_day_GPCP-1-3_PCMDI_gn_19961002-20170101.nc
> Generating land sea mask.
> Generating precipitation block extrema.
> Writing results to netCDF.
> No sftlf file found for GISS-E2-H r6i1p1
> 
> -----------------------
> model, run, variable: GISS-E2-H r6i1p1 pr
> test_data (model in this case) full_path:
>    demo_output/extremes_tmp/pr_day_GISS-E2-H_historical_r6i1p1_20000101-20051231.nc
> Generating land sea mask.
> Generating precipitation block extrema.
> Writing results to netCDF.
> Generating metrics.
> Traceback (most recent call last):
>   File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/bin/extremes_driver.py", line 458, in <module>
>     result_dict = compute_metrics.metrics_json(
>   File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/compute_metrics.py", line 565, in metrics_json
>     obs_m = obs_dict[m].regridder.horizontal(
>   File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/xcdat/regridder/accessor.py", line 323, in horizontal
>     regridder = regrid_tool(input_grid, output_grid, **options)
>   File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/xcdat/regridder/regrid2.py", line 52, in __init__
>     self._dst_lat = self._output_grid.bounds.get_bounds("Y")
>   File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/xcdat/bounds.py", line 247, in get_bounds
>     raise KeyError(
> KeyError: "No bounds data variables were found for the 'Y' axis. Make sure the dataset has bound data vars and their names match the 'bounds' attributes found on their related time coordinate variables. Alternatively, you can add bounds with `ds.bounds.add_missing_bounds()` or `ds.bounds.add_bounds()`."
> ```

@lee1043 At this point the obs dataset should have bounds because the last change I made was to move the call to add_missing_bounds() into the obs preprocessing section of compute_metrics. So I need to see if this is a data issue or a code issue.

**Comment by lee1043** [comment]
I think this reminds me that I have seen a similar issue which was occurred by regrid2 of xcdat was dropping bounds information after interpolating. I cannot recall this issue was reported to the xcdat team, if not, I will report it. During the mean time, I think a workaround could be after the regrid2 interpolation, apply add_missing_bounds, to re-add bounds information.

**Comment by lee1043** [comment]
@acordonez I have to retracrt my above comment because it seems it might not be the case for this error, because the error was coming from [here](https://github.com/PCMDI/pcmdi_metrics/blob/153fe1f67a2d635c3796a9115b2c0d68b63e8a9a/pcmdi_metrics/extremes/lib/compute_metrics.py#L565):
```python
                    obs_m = obs_dict[m].regridder.horizontal(
                        season, target, tool="regrid2"
                    )
```
Could you check if `obs_dict[m]` have bounds in it?

**Comment by acordonez** [comment]
@lee1043  I think I see the issue, there is a second function that would need the add_missing_bounds call. But I'm seeing if there's somewhere in the driver I can put it so I'm not adding bounds to the same dataset over and over.

**Comment by acordonez** [comment]
@lee1043 I did some more digging and obs_dict[m] definitely has bounds. This screenshot shows the outputs of some print statements before line 565 when the code fails. The dataset has the lat_bnds, lon_bnds, and time_bnds variables, and lat, lon, and time all have the bounds attribute. Along with that, the input dataset definitely has bounds, and earlier in the code I explicitly check for missing bounds. So I'm stumped why this call is failing.

Screenshot 2023-12-22 at 1 56 10 PM

**Comment by acordonez** [comment]
@lee1043 In the error message it looks like maybe it's the target grid that's missing bounds?

**Comment by lee1043** [comment]
> @lee1043 In the error message it looks like maybe it's the target grid that's missing bounds?

That could be, as the error was coming from the line with `output_grid`, but that is still strange... as I was expecting it supposed to be handled by xCDAT. Can you create a minimal code to reproduce this error, with saving the `obs_dict[m]` as a netcdf file as an input for the minimal code, and then open an issue in xCDAT repo?

**Comment by acordonez** [comment]
@lee1043 I added bounds to the target grid and am still seeing the issue. I'll work on an example for an issue.

**Comment by acordonez** [comment]
> @lee1043 I added bounds to the target grid and am still seeing the issue. I'll work on an example for an issue.

Actually adding bounds to the target might have fixed the issue, I think I'm seeing an error in a different part of the code now.

**Comment by acordonez** [comment]
@lee1043 Sorry for all the back-and-for but this new change adds bounds to the target grid for regridding, and works on my end.

**Comment by lee1043** [comment]
@acordonez thank you for the fix. The code runs without the error, but the output json does not look right. Thank you for patiently addressing these issues!

```
extremes_driver.py  -p basic_extremes_param.py
```
```python
import os
import json
output_path = os.path.join(demo_output_directory, "extremes_ex1/GISS-E2-H_block_extremes_metrics.json")
with open(output_path) as f:
    metric = json.load(f)["RESULTS"]
print(json.dumps(metric, indent=2))
```
```
{
  "GISS-E2-H": {
    "r6i1p1": {
      "Rx1day": {
        "land": {
          "mean": {
            "ANN": NaN,
            "DJF": NaN,
            "JJA": NaN,
            "MAM": NaN,
            "SON": NaN
          },
          "std_xy": {
            "ANN": NaN,
            "DJF": NaN,
            "JJA": NaN,
            "MAM": NaN,
            "SON": NaN
          }
        }
      },
      "Rx5day": {
        "land": {
          "mean": {
            "ANN": NaN,
            "DJF": NaN,
            "JJA": NaN,
            "MAM": NaN,
            "SON": NaN
          },
          "std_xy": {
            "ANN": NaN,
            "DJF": NaN,
            "JJA": NaN,
            "MAM": NaN,
            "SON": NaN
          }
        }
      }
    }
  }
}
```

And maybe related on this, it seems below error is coming from plotting.
```
extremes_driver.py  -p basic_extremes_param.py --case_id "extremes_ex3" --plots
```
```
Metrics output path not found.
Creating metrics output directory demo_output/extremes_ex3
No sftlf file found for GISS-E2-H r6i1p1

-----------------------
model, run, variable: GISS-E2-H r6i1p1 pr
test_data (model in this case) full_path:
   demo_output/extremes_tmp/pr_day_GISS-E2-H_historical_r6i1p1_20000101-20051231.nc
Generating land sea mask.
Generating precipitation block extrema.
Writing results to netCDF.
Creating maps
Traceback (most recent call last):
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/bin/extremes_driver.py", line 431, in <module>
    meta = plot_extremes.make_maps(
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/plot_extremes.py", line 19, in make_maps
    plot_extremes(data, index, model, run, yrs, output_template)
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20231129/lib/python3.10/site-packages/pcmdi_metrics/extremes/lib/plot_extremes.py", line 44, in plot_extremes
    min_lev = math.floor(ds.min() [/](https://file+.vscode-resource.vscode-cdn.net/) 10) * 10
ValueError: cannot convert float NaN to integer
```

**Comment by acordonez** [comment]
@lee1043 This latest commit fixed the all-Nan issue you flagged on my end. The notebook ran all the way for me and I'm hoping it runs for you!

**Review by lee1043 — APPROVED** [review]

**Pull request merged**
