### PR TITLE
Port cdat_info functions

### LINKED ISSUE #1003: [Feature]: Port cdat_info dependencies to PMP
### Is your feature request related to a problem?

PMP is currently dependent on cdat_info, which has been sunsetted. We need an alternative to using cdat_info for downloading sample data files and generating provenance.

Here are references to where the PMP calls cdat_info:

download_sample_data_files: PMP [ex1](https://github.com/PCMDI/pcmdi_metrics/blob/959a5277c07453174ddd91e80b876df29db2f43b/pcmdi_metrics/misc/scripts/get_pmp_data.py#L63), [ex2](https://github.com/PCMDI/pcmdi_metrics/blob/959a5277c07453174ddd91e80b876df29db2f43b/doc/jupyter/Demo/Demo_0_download_data.ipynb#L98), [source](https://github.com/CDAT/cdat_info/blob/master/cdat_info/cdat_info_src.py#L326)
generate_provenance: [PMP](https://github.com/PCMDI/pcmdi_metrics/blob/main/pcmdi_metrics/io/base.py#L91),  [source](https://github.com/CDAT/cdat_info/blob/master/cdat_info/provenance.py#L35)
get_sampledata_path: [PMP](https://github.com/PCMDI/pcmdi_metrics/blob/main/tests/deprecated/test_pmp_monsoon_sperber.py#L19) (deprecated but listing for completion), [source](https://github.com/CDAT/cdat_info/blob/master/cdat_info/cdat_info_src.py#L108)

### Describe the solution you'd like

cdat_info uses the same license as the PMP (BSD-3 Clause), a license which would let us reuse cdat_info source code. I propose copying over the download_sample_data_files and generate_provenance functions to the PMP. They may need some changes to integrate with the PMP, but this looks reasonable to me.

### Describe alternatives you've considered

We could look for other libraries or build custom solutions from scratch, but those would both likely take more time and effort.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by acordonez**
1. cdat_info.download_sample_data_files has been copied to base.io with some minor changes. The Demo 0 notebook and Demo 6 notebook have been run with the updated import statement.
2. cdat_info.provenance.generateProvenance and dependencies have been copied to base.io with some minor changes. I have combined it with the changes that are currently in base.generateProvenance such as the added packages to record. I have removed references to packages like VCS that are no longer PMP dependencies.

I have not copied cdat_info.get_sampledata_path() because there are no references to it in the PMP production code.

I have removed all references to cdat_info except in deprecated code.

Closes #1003

### CODE REVIEW

**Comment by acordonez** [comment]
Still waiting on ENSO notebook testing.

**Comment by acordonez** [comment]
> Still waiting on ENSO notebook testing.

Pushed update to ENSO notebook. Now need to debug testing failure.

**Comment by acordonez** [comment]
The line throwing the error (106: __author__ = msg["Author"]) is not found in recent versions of [esmpy/__init__.py](https://github.com/esmf-org/esmf/blob/patch/8.6.1/src/addon/esmpy/src/esmpy/__init__.py). I'm trying to figure out what version is getting pulled by the test suite and if there's a way to grab a newer version.
This esmpy issue provides some additional background: https://github.com/esmf-org/esmf/issues/140

**Comment by acordonez** [comment]
Tried pinning the esmpy version to > 8.4.2 but that caused a failure in setting up the test conda environment. Now trying to pin importlib_metadata to an older version that does not raise the error.

**Comment by acordonez** [comment]
It looks like pinning the importlib_metadata version actually got the test to run successfully. This pin should be removed when we're able to figure out a dev environment that uses a newer esmpy version.

**Comment by acordonez** [comment]
I've created a fix for the build problems in https://github.com/PCMDI/pcmdi_metrics/pull/1107.

**Review by lee1043 — APPROVED** [review]

**Pull request merged**
