### PR TITLE
xcdat version update

### PR DESCRIPTION
**Pull request by lee1043**
Update xcdat version to [0.7.2](https://github.com/xCDAT/xcdat/releases/tag/v0.7.2) in dev.yml

### CODE REVIEW

**Comment by lee1043** [comment]
@acordonez could you take a look if there is any other place to make change if I am missing?

**Comment by acordonez** [comment]
@lee1043 Is the latest xcdat required? If so, we can update the meta.yaml file in the conda-feedstock when releasing the new version. If it's not required, I don't see anywhere else to update.

**Comment by lee1043** [comment]
@acordonez yes, some capability in the latest xcdat is required to run PMP for piControl simulations. Thank you for pointing out about the meta.yaml. Could you please update it when we release the new version?

**Comment by acordonez** [comment]
@lee1043 Can do. I'm just testing that the dev.yml works for creating a new environment then I'll approve.

**Review by acordonez — APPROVED** [review]

**Pull request merged**
