### PR TITLE
Switch to setuptools

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@muryanto1 I have to look at this carefully again. Even though I technically didn't touch any code (just reshuffling) It says big drop in coverage. Do you think it's because of bin files? They're now called via `entry_point`. Maybe some test silently fail... At least we can now see the coverage in files from the PR. Which was the goal on this PR.

**Comment by doutriaux1** [comment]
@muryanto1 it finally passes all os and ci systems. Please review.

**Comment by doutriaux1** [comment]
@durack1 @gleckler1 @lee1043  please take a look as well, there's no new functionalities, but this gives us, better coverage report and ONE common upload for all OSes and Python flavors.

**Comment by gleckler1** [comment]
@durack1 @gleckler1 @lee1043.  I am ok with the dir/filename reorg.   Is the test suite sufficiently comprehensive to check that nothing has broken?   Probably we should rerun all of our CMIP5 results soon to verify.

**Comment by doutriaux1** [comment]
@gleckler1 it's one the bonus things, the "coverage" is now reporting a 14% increase, because we can now report on coverage from tests launch in subprocess. Total coverage for the test suite says 60.5%. But most of it comes from test. Actually I see that diurnal tests coverage is not being reported. I'll take a look in another PR. @muryanto1 can you help me investigate this?. See: https://coveralls.io/builds/19960332

**Comment by doutriaux1** [comment]
@muryanto1 actually we're still not reporting coverage correctly on things coming from subprocesses... Such a pain. I see nothing from diurnal and most of the code ran by metrics driver is left uncovered...

**Comment by durack1** [comment]
@doutriaux1 once this is in, there will NEED to be a new release. 1.2 from Sept is a long time, and many code/dir/org changes ago

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 New release is fine but we need to have examples in it and that is contingent on C and Z getting CDP working with code in input param files.

**Comment by doutriaux1** [comment]
@gleckler1 I'm trying to contact @zshaheen to understand how to trigger his changes.

**Comment by doutriaux1** [comment]
@gleckler1 if it's not a new file it will be migrated smoothly. If not I'll help you do the cleanup.

**Pull request merged**
