### PR TITLE
portrait plot bug fix in python 3 env

### PR DESCRIPTION
**Pull request by lee1043**
https://github.com/PCMDI/pcmdi_metrics/issues/581

make sure integer number used for reshape array, where python 3 returns integer/integer = float

### CODE REVIEW

**Comment by doutriaux1** [comment]
@lee1043 feel free to merge if tests pass.

**Comment by lee1043** [comment]
@doutriaux1 hmm... it says travis-ci fails, not sure what to do. May I hand over this to you?

**Comment by lee1043** [comment]
@doutriaux1 travis still fails....

**Comment by doutriaux1** [comment]
@lee1043 yes, it was expected, but output should be more readable now.

**Pull request merged**
