### PR TITLE
CMEC Driver support

### PR DESCRIPTION
**Pull request by acordonez**
These changes add support to run PMP metrics via cmec-driver. By default, this set-up will use the PMP demo data to run the metrics out-of-the-box. To run with different data, make changes in cmec-driver/config/cmec.json.

Along with the settings JSONs and driver scripts required by cmec-driver (in the "cmec" folder), I made small changes to a few other scripts. In pcmdi_metrics/pcmdi/scripts/pcmdi_compute_climatologies.py there is a fix for the case where the start and end years are not provided. In the Base write_cmec function I removed the "indices" key from under "statistics" since this convention was copied from ILAMB, which generates indices as metrics, but doesn't apply to PMP. In Monsoon (Sperber) I added support for generating a CMEC-compliant results JSON.

### PCMDI Metrics
1. Pull PMP branch 742_ao_cmec_driver and run python setup.py install (needed to get AC fix and monsoon_sperber cmec option)
2. Download the PMP demo data if you do not already have it.
3. Install the cmec pcmdi metrics environment: Inside the pcmdi_metrics parent directory, do `conda env create --file cmec/cmec_pcmdi_metrics.yml`

#### Setup:
1. Clone cmec-driver (https://github.com/cmecmetrics/cmec-driver)
2. Enter cmec-driver parent directory
3. Create an output directory: `mkdir output`
4. (first-time use) Register conda env info with cmec-driver:  
    `python cmec-driver.py setup -conda_source <path to conda.sh> -env_root <path to conda envs folder>
5. Register the PMP: `python cmec-driver.py register <path_to_pcmdi_metrics>`
6. Check that module is registered: `python cmec-driver.py list -all`
7. Once module is registered, the default settings are populated in config/cmec.json. These settings can be edited in this file before running the metrics.

#### Test Run
Generic command: `python cmec-driver.py run -obs <obs_dir> <model_dir> <output_dir> Module/configuration`
Example: `python cmec-driver.py run -obs demo_data/ demo_data/ output/ PMP/monsoon_wang` (demo data path is provided twice - once for obs, and once for model).
Results for this run are located in output/PMP/monsoon_sperber.   
Note for mean_climate: When using the demo data, include the PCMDIobs2_clims folder name in your obs directory.

## Metrics Names (Configurations)
mean_climate
diurnal_cycle
monsoon_wang
monsoon_sperber
variability_modes
mjo

# Future improvements
As noted in Issue 742, there are a few remaining changes for CMEC compliance and ease of use that are not included in this PR.

### CODE REVIEW

**Comment by acordonez** [comment]
@gleckler1 @lee1043 Here's what I have so far for the PMP CMEC driver support. All the metrics are set up to run using the demo data out-of-the-box.

**Comment by acordonez** [comment]
@gleckler1 @lee1043 I've updated this branch and it is ready to merge once CircleCi finishes. I see under the "Merge pull request" button (down arrow on right) that there is an option to "Squash and Merge" - since I have a pretty messy commit history, can we use this option?

**Comment by lee1043** [comment]
@acordonez I never knew about the "Squash and Merge" option for merging, so it's good to learn about it -- thanks! I have no prob with using that option.

**Review by lee1043 — APPROVED** [review]
This is indeed a very nice and important accomplishment. Thank you, @acordonez, for your hard work!

**Pull request merged**
