### PR TITLE
Issue292 pjg addzonalmean

### PR DESCRIPTION
**Pull request by gleckler1**
work in progress but currently functional

### CODE REVIEW

**Comment by durack1** [comment]
@gleckler1 great this is looking ALOT cleaner..

**Comment by gleckler1** [comment]
@doutriaux1 This pull request - maybe after major repair - needs to be merged in time for V1.1

**Comment by doutriaux1** [comment]
@gleckler1 tiny tweaks please review and let me know if that's ok with you.

**Comment by gleckler1** [comment]
@doutriaux1 I'll give it a test run and get back to you shortly.

**Comment by gleckler1** [comment]
@doutriaux1 I went to branch did a pull, so some changes come down... when I ran a test I don't see the zonal mean (and departure results) and more but the following was inadvertently appended to the json:
    "METRICS": {
        "rms_xyt": {
            "Abstract": "Compute Spatial and Temporal Root Mean Square",
            "Contact": "Peter Gleckler <gleckler1@llnl.gov>",
            "Name": "Spatio-Temporal Root Mean Square",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "rms_xy": {
            "Abstract": "Compute Spatial Root Mean Square",
            "Contact": "Peter Gleckler <gleckler1@llnl.gov>",
            "Name": "Spatial Root Mean Square",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "bias_xy": {
            "Abstract": "Compute Full Average of Model - Observation",
            "Contact": "Peter Gleckler <gleckler1@llnl.gov>",
            "Name": "Bias"
        },
        "mae_xy": {
            "Abstract": "Compute Full Average of Absolute Difference Between Model And Observation",
            "Contact": "Peter Gleckler <gleckler1@llnl.gov>",
            "Name": "Mean Absolute Error"
        },
        "cor_xyt": {
            "Abstract": "Compute Spatio-Temporal Correlation",
            "Contact": "Peter Gleckler <gleckler1@llnl.gov>",
            "Name": "Spatial and Temporal Correlation",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "cor_xy": {
            "Abstract": "Compute Spatial Correlation",
            "Contact": "Peter Gleckler <gleckler1@llnl.gov>",
            "Name": "Spatial Correlation",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        },
        "seasonal_mean": {
            "Abstract": "Compute Seasonal Mean",
            "Contact": "Peter Gleckler <gleckler1@llnl.gov>",
            "Name": "Seasonal Mean",
            "Comments": "Assumes input are 12 months climatology"
        },
        "annual_mean": {
            "Abstract": "Compute Annual Mean",
            "Contact": "Peter Gleckler <gleckler1@llnl.gov>",
            "Name": "Annual Mean",
            "Comments": "Assumes input are 12 months climatology",
            "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
        }

**Comment by gleckler1** [comment]
@doutriaux1 my bad... its working

**Comment by doutriaux1** [comment]
@gleckler1 I did run locally here's my diff and it shows only the new stuff that this branch adds.

Remember @jservonnat asked for the metrics description to be always added so your extra bits are normal.

Here's my diff:

```
doutriaux1@maryam:[pcmdi_metrics]:[issue292_pjg_addzonalmean+99]:[491]> diff pcmdi_install_test_results/metrics_results/installationTest/tas_2.5x2.5_regrid2_linear_metrics.json /git/pcmdi_metrics/test/pcmdi/installationTest/tas_2.5x2.5_regrid2_linear_metrics.json
106,109d105
<                     "rms_devzm_ann_GLB": "1.394",
<                     "rms_devzm_ann_NHEX": "1.935",
<                     "rms_devzm_ann_SHEX": "1.244",
<                     "rms_devzm_ann_TROPICS": "1.112",
134,137d129
<                     "rms_y_ann_GLB": "2.103",
<                     "rms_y_ann_NHEX": "2.725",
<                     "rms_y_ann_SHEX": "2.200",
<                     "rms_y_ann_TROPICS": "0.999",
202,205d193
<                     "rms_devzm_ann_GLB": "1.806",
<                     "rms_devzm_ann_NHEX": "1.903",
<                     "rms_devzm_ann_SHEX": "2.249",
<                     "rms_devzm_ann_TROPICS": "1.558",
230,233d217
<                     "rms_y_ann_GLB": "1.676",
<                     "rms_y_ann_NHEX": "1.970",
<                     "rms_y_ann_SHEX": "1.778",
<                     "rms_y_ann_TROPICS": "1.245",
298,301d281
<                     "rms_devzm_ann_GLB": "1.028",
<                     "rms_devzm_ann_NHEX": "1.514",
<                     "rms_devzm_ann_SHEX": "0.890",
<                     "rms_devzm_ann_TROPICS": "0.902",
326,329d305
<                     "rms_y_ann_GLB": "2.452",
<                     "rms_y_ann_NHEX": "3.425",
<                     "rms_y_ann_SHEX": "2.216",
<                     "rms_y_ann_TROPICS": "1.056",
387,393d362
<         "zonal_mean": {
<             "Abstract": "Compute Zonal Mean",
<             "Contact": "Peter Gleckler <gleckler1@llnl.gov>",
<             "Name": "Zonal Mean",
<             "Comments": "",
<             "URI": "http://uvcdat.llnl.gov/documentation/utilities/utilities-2.html"
<         },
405,406c374,375
<     "metrics_git_sha1": "69c22a915eb668703872d28ba533f604dfe6dd01",
<     "uvcdat_version": "2.4.1"
---
>     "metrics_git_sha1": "feb97cf6ef96a4e01c25081f492e51874d46485e",
>     "uvcdat_version": "v2.5.0-53-g6522555"
```

**Pull request merged**
