### PR TITLE
Fixes determining resource path

### PR DESCRIPTION
**Pull request by jasonb5**
Adds a function to return a path to the package resources. 
The function checks the following locations in order.
1. Under CONDA_PREFIX (checks if path exists or continues)
2. Using pkg_resources
3. Current directory

### CODE REVIEW

**Comment by jasonb5** [comment]
@acordonez After we merge this we can add a patch to the staged recipe.

**Comment by lee1043** [comment]
@jasonb5 thanks for the PR. The github action build test fails with following message, could you please check?

```
Traceback:
/usr/share/miniconda/envs/pcmdi_metrics_dev/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_resources.py:4: in <module>
    from pcmdi_metrics import resources
E   ModuleNotFoundError: No module named 'pcmdi_metrics'
```

**Comment by jasonb5** [comment]
`pytest` fails while `python -m pytest` works, I'm guessing it's an issue with `sys.path`.

@tomvothecoder  any idea why this might not be working, the workflow looks identical to xcdat's which works using just `pytest`.

**Comment by tomvothecoder** [comment]
@jasonb5 The tests directory was missing an `__init__.py` file so it was throwing `ModuleNotfoundError`.

I made a PR fix on your fork to merge to this branch https://github.com/jasonb5/pcmdi_metrics/pull/1, which should fix the build on this PR.

**Comment by jasonb5** [comment]
@tomvothecoder Ah totally missed that, makes sense now. thanks

**Review by lee1043 — APPROVED** [review]

**Review by acordonez — APPROVED** [review]
Thank you Jason! The jupyter notebook demos all ran smoothly for me with this change.

**Pull request merged**
