### PR TITLE
627 ljw mov parallel 2

### PR DESCRIPTION
**Pull request by lee1043**
- Resolve Issue #627
- Here, the changes were migrated from PR https://github.com/PCMDI/pcmdi_metrics/pull/628 because the previous branch was based on outdated master and rebase process was not going smooth.

### CODE REVIEW

**Comment by lee1043** [comment]
NOTE: Some more cleaning up and checking needed before fully merging to master. Please do not merge this until told.

**Comment by lee1043** [comment]
@gleckler1 I believe this branch is ready to be merged.

**Comment by gleckler1** [comment]
@lee1043  Before we merge this with master lets first settle on where to put our in-house param files, e.g., 

/variability_mode/doc/myParam_test.py → ...ariability_mode/param/myParam_demo_NAM.py 

We know have another PR with a proposal of where to put these ;-)

There are some failures with the circleci tests, but I recall you indicated Lina suggested we can live with them.   Do you know if they will they count against our "success" rate?

**Comment by lee1043** [comment]
@muryanto1 Some tests are still failing even after I have taken care of all flake8 related issues. I see below log from circle ci, any chance that is looking familiar to you?
```
CondaHTTPError: HTTP 504 GATEWAY TIME-OUT for url <https://conda.anaconda.org/cdat/label/nightly/linux-64/vtk-cdat-8.2.0.8.2.2020.07.20.18.56.g3aa9eaf-py36_mesalibh3081630_0.tar.bz2>
Elapsed: 01:00.037931
CF-RAY: 5ed3f105c8e92598-IAD

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

**Comment by muryanto1** [comment]
@lee1043 HTTP Error indicates there is a network issue in circle ci at the time the test ran, please do "Rerun Workflow from Failed" in circleci.

**Comment by lee1043** [comment]
@muryanto1 will do, thank you very much for your comment.

**Comment by lee1043** [comment]
@gleckler1 internal parameter files were moved to [under the sample_setups directory](https://github.com/PCMDI/pcmdi_metrics/tree/627_ljw_MoV_parallel_2/sample_setups/pcmdi_parameter_files/variability_modes)

**Comment by gleckler1** [comment]
@lee1043 It looks like the job has stalled because we are using the free version.

**Comment by gleckler1** [comment]
@lee1043 Shall I merge this now?

**Comment by lee1043** [comment]
@gleckler1 yes please :)

**Pull request merged**
