### PR TITLE
Monsoon Wang plots on the fly

### PR DESCRIPTION
**Pull request by lee1043**

### CODE REVIEW

**Comment by lee1043** [comment]
@acordonez when you get a chance, could you please run demo 2a with the PR to see if it run smoothly?

**Comment by acordonez** [comment]
@lee1043 I'm getting this error on the first run in Notebook 2a. I am using this branch and reran Demo 0 to regenerate the parameter files first.

```
>>>monsoon_wang_driver.py -p basic_monsoon_wang_param.py
/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/pcmdi_metrics/utils/string_constructor.py:43: UserWarning: Keyword 'model' not provided for filling the template.
  warnings.warn(f"Keyword '{k}' not provided for filling the template.")

modelFile =   demo_data_tmp/CMIP5_demo_clims/cmip5.historical.CanCM4.r1i1p1.mon.pr.198101-200512.AC.v20200426.nc
dom =   AllMW

Traceback (most recent call last):
  File "/home/ordonez4/miniconda3/envs/pmp_dev/bin/monsoon_wang_driver.py", line 245, in <module>
    monsoon_wang_runner(args)
  File "/home/ordonez4/miniconda3/envs/pmp_dev/bin/monsoon_wang_driver.py", line 174, in monsoon_wang_runner
    ds_out = xr.Dataset(
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/xarray/core/dataset.py", line 685, in __init__
    variables, coord_names, dims, indexes, _ = merge_data_and_coords(
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/xarray/core/dataset.py", line 416, in merge_data_and_coords
    return merge_core(
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/xarray/core/merge.py", line 719, in merge_core
    variables, out_indexes = merge_collected(
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/xarray/core/merge.py", line 290, in merge_collected
    merged_vars[name] = unique_variable(
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/xarray/core/merge.py", line 144, in unique_variable
    raise MergeError(
xarray.core.merge.MergeError: conflicting values for variable 'time' on objects to be combined. You can skip this check by specifying compat='override'.
[WARNING] yaksa: 10 leaked handle pool objects
```

**Comment by acordonez** [comment]
@lee1043 Realized I was using an old environment and needed to update xcdat. But now I am seeing this issue. I am using numpy version 2.0.2 - what version of numpy should I be testing this with?
```
Traceback (most recent call last):
  File "/home/ordonez4/miniconda3/envs/pmp_dev/bin/monsoon_wang_driver.py", line 10, in <module>
    import pcmdi_metrics
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/pcmdi_metrics/__init__.py", line 17, in <module>
    from . import io
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/pcmdi_metrics/io/__init__.py", line 28, in <module>
    from .region_from_file import region_from_file
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/pcmdi_metrics/io/region_from_file.py", line 4, in <module>
    import regionmask
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/regionmask/__init__.py", line 3, in <module>
    from . import core, defined_regions
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/regionmask/defined_regions/__init__.py", line 3, in <module>
    from . import _natural_earth, _ressources
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/regionmask/defined_regions/_natural_earth.py", line 14, in <module>
    from ..core.regions import Regions
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/regionmask/core/regions.py", line 15, in <module>
    from .mask import _inject_mask_docstring, _mask_2D, _mask_3D
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/regionmask/core/mask.py", line 534, in <module>
    lon, lat, polygons, numbers, fill=np.NaN, is_unstructured=False, as_3D=False
  File "/home/ordonez4/miniconda3/envs/pmp_dev/lib/python3.10/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.. Did you mean: 'nan'?
[WARNING] yaksa: 10 leaked handle pool objects
```

**Comment by lee1043** [comment]
@acordonez thank you for testing. Can you tell what the version of `regionmask` is in your env?

**Comment by lee1043** [comment]
It looks like we have to use `regionmask >= v0.11.0` according to https://github.com/regionmask/regionmask/issues/440. Could you check if this issue continues when you update `regionmask` version?

**Comment by lee1043** [comment]
@acordonez In dev.yml and ci.yml, I see the dependency list that includes `regionmask=0.12.1`

**Comment by acordonez** [comment]
@lee1043 Thanks, the notebook ran for me with this fix. Is there anything in particular I should look at?

**Review by acordonez — APPROVED** [review]

**Pull request merged**
