### PR TITLE
possible fix for #461

### PR DESCRIPTION
**Pull request by zshaheen**

### CODE REVIEW

**Comment by zshaheen** [comment]
@doutriaux1 @durack1 This solves #461, #457. As of this comment, Travis finished the test for this PR, yet there was no upload to Anaconda.

**Comment by doutriaux1** [comment]
@zshaheen actually the build https://travis-ci.org/PCMDI/pcmdi_metrics/builds/189610854 did not upload. I think all I needed to do was to disable build/test for things that are NOT PRs.

**Comment by doutriaux1** [comment]
@zshaheen tsk tsk self merging :wink: let's see if your change still uploads once it's merged in master.

**Comment by zshaheen** [comment]
@doutriaux1 Well, it seems like it doesn't retest when merging a pull request (maybe because it already tested it), so there's no new upload to Anaconda 😞 . I'll revert the change.

**Comment by doutriaux1** [comment]
do not revert @zshaheen I triggered build for every pull again.

**Comment by zshaheen** [comment]
@doutriaux1 Okay, so are we good now?

**Comment by doutriaux1** [comment]
testing that it does not upload again at: https://travis-ci.org/PCMDI/pcmdi_metrics/builds/189622073

**Comment by doutriaux1** [comment]
i think we are. It's kind of sad to build for every push... maybe i will turn off the build for PR now since we build for every push.

**Comment by doutriaux1** [comment]
hummm @zshaheen what do you think of: The command "python test/test_suite.py -V" exited with 0.
after_success
0.01s$ test $TRAVIS_BRANCH = "master" && $TRAVIS_PULL_REQUEST = "false" && conda install conda-build && conda install anaconda-client && bash conda-recipes/pcmdi_metrics/conda_upload.sh
/home/travis/build.sh: line 57: 460: command not found

**Comment by zshaheen** [comment]
@doutriaux1 Oh I get it. If you look [here](https://docs.travis-ci.com/user/environment-variables/), `TRAVIS_PULL_REQUEST` is the number of the pull request, which is 460 in our case and not some boolean.

**Comment by zshaheen** [comment]
@doutriaux1 Just to confirm, it's still not working right?

**Comment by doutriaux1** [comment]
not sure

**Comment by zshaheen** [comment]
I fixed the `/home/travis/build.sh: line 57: 460: command not found` error on my fork. If it still doesn't work, let me know and I'll try what I got.

**Pull request merged**
