### PR TITLE
540 pjg jsonusernotes param

### PR DESCRIPTION
**Pull request by gleckler1**
@doutriaux1 @zshaheen   Working toward weening off "legacy" !  This PR includes 2 desperately needed parameter file enhancements.  1) added functionality to construct json filename from parameter file, and 2) added "user_notes" to parameter file.

### CODE REVIEW

**Comment by gleckler1** [comment]
@doutriaux1 @zshaheen  Can one of you pls check/fix how I have added json_filename and user_notes in the PR request.   I need this to start with regridding tests and to start organizing jsons from different metrics.   And here is your chance to ween me off legacy!

**Comment by doutriaux1** [comment]
@gleckler1 I also noticed we currently have a param named `filename_output_template` which is used for climatologies. Should we rename this to something more appropriate like `climatologies_output_template` ?

**Comment by doutriaux1** [comment]
@zshaheen actually it looks like it broke some test. I will need your input to find the magical invocation

**Comment by gleckler1** [comment]
@doutriaux1  Looks great!   Should I try this our before merging?

**Comment by doutriaux1** [comment]
@gleckler1 would be nice. Also mac is failing but it seems to be vtk-cdat related I'm looking into this.

**Comment by gleckler1** [comment]
@doutriaux1 looks to me like its working... I think we are ready to roll!  Do I get to push the little green button?

**Comment by doutriaux1** [comment]
Go ahead! Have fun @gleckler1 !

**Pull request merged**
