### PR TITLE
testing new vcs

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@scottwittenburg let's look at these as well

**Comment by scottwittenburg** [comment]
@doutriaux1, will do.

**Comment by scottwittenburg** [comment]
@doutriaux1 The `vcs` [PR](https://github.com/CDAT/vcs/pull/376) fixed the logo stretching for me locally, but some of the other tests I couldn't run due to some missing json files.  For example:

```console
()
()
()
()
---------------------------------------------------
('RUNNING:', '/data/scott/projects/pcmdi/pcmdi_metrics/tests/pcmdi/basic_test_parameters_file.py')
---------------------------------------------------
()
()
()
()
E
======================================================================
ERROR: testParam (test_pmp_basic_test_parameters_file.PMPParamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/scott/projects/pcmdi/pcmdi_metrics/tests/test_pmp_basic_test_parameters_file.py", line 7, in testParam
    self.runPMP(param)
  File "/data/scott/projects/pcmdi/pcmdi_metrics/tests/basepmpdriver.py", line 34, in runPMP
    parser = create_mean_climate_parser()
  File "/data/scott/projects/pcmdi/pcmdi_metrics/pcmdi_metrics/pcmdi/mean_climate_metrics_driver.py", line 223, in create_mean_climate_parser
    parser = pcmdi_metrics.driver.pmp_parser.PMPMetricsParser()
  File "/data/scott/projects/pcmdi/pcmdi_metrics/pcmdi_metrics/driver/pmp_parser.py", line 24, in __init__
    *args, **kwargs)
  File "/data/scott/Documents/miniconda2/envs/cdat-nightly-ogl2/lib/python2.7/site-packages/cdp/cdp_parser.py", line 30, in __init__
    self.load_default_args(default_args_file)
  File "/data/scott/Documents/miniconda2/envs/cdat-nightly-ogl2/lib/python2.7/site-packages/cdp/cdp_parser.py", line 580, in load_default_args
    if self.load_default_args_from_json(files):
  File "/data/scott/Documents/miniconda2/envs/cdat-nightly-ogl2/lib/python2.7/site-packages/cdp/cdp_parser.py", line 516, in load_default_args_from_json
    with open(afile) as json_file:
IOError: [Errno 2] No such file or directory: '/data/scott/Documents/miniconda2/envs/cdat-nightly-ogl2/share/cia/DefArgsCIA.json'

----------------------------------------------------------------------
Ran 1 test in 0.005s

FAILED (errors=1)
```

**Comment by doutriaux1** [comment]
@scottwittenburg you need to add the `cia` package from `pcmdi/label/nightly` conda channel.

**Comment by doutriaux1** [comment]
@scottwittenburg looks like the logo is still stretched here.

**Comment by scottwittenburg** [comment]
@doutriaux1 I don't think I get how it should have been fixed here if the fix hasn't been merged in `vcs` yet.

**Comment by doutriaux1** [comment]
@scottwittenburg yes, too many PR and issues at once in my browser (and head). Testing on my mac here. Please add a test to the vcs branch though.

**Comment by doutriaux1** [comment]
@scottwittenburg your vcs fix makes pcmdi_metrics pass w/o changes! As soon as you add the test I will merge in. Thx!

**Pull request merged**
