### PR TITLE
On-the-fly mean clim plot generation 

### PR DESCRIPTION
**Pull request by lee1043**

### CODE REVIEW

**Comment by lee1043** [comment]
So far, this will partially resolves #1111.

**Comment by lee1043** [comment]
@acordonez this PR is to add plot generation for the mean climate metrics. I confirmed the demo1a and b notebooks are working well on my end, but could you help on reviewing this PR and run Demo 1 to confirm it works well on your end?

**Comment by lee1043** [comment]
By https://github.com/PCMDI/pcmdi_metrics/pull/1162/commits/02f2c3526306a20127ff3f95fd075dc98668532d, this PR now addresses #1111

**Review by acordonez — APPROVED** [review]
@lee1043 I ran Demo 1a and 1b and both completed successfully. Looks like we will need to add colorcet as a new dependency in conda-forge?

**Comment by lee1043** [comment]
> @lee1043 I ran Demo 1a and 1b and both completed successfully. Looks like we will need to add colorcet as a new dependency in conda-forge?

Yes, we will need to add colorcet. Thank you for taking care of the conda-forge part.

**Comment by lee1043** [comment]
@acordonez And thank you for the review! Glad to know that it was running without error on your end.

**Pull request merged**
