### PR TITLE
Add data files and model mask to sea ice metrics

### PR DESCRIPTION
**Pull request by acordonez**
This PR accomplishes four things:
1. Adds a data file to the output bundle that includes the time mean sea ice and climatology.
2. Fixes a bug where the land sea mask was not applied to models.
3. Reports the MSE for the climatology without the mean included
4. Changes the y-axis settings on the output figure

### CODE REVIEW

**Comment by lee1043** [comment]
@acordonez thanks for the PR, I am running [demo 9 notebook](https://github.com/PCMDI/pcmdi_metrics/blob/main/doc/jupyter/Demo/Demo_9_seaIceExtent_ivanova.ipynb) with this PR.

**Comment by lee1043** [comment]
@acordonez I checked the demo 9 notebook runs without error. But considering the graphics changed with the PR, could you please also update the notebook? Or I can also help update, let me know.

**Comment by acordonez** [comment]
@lee1043 Yes I can rerun the notebook.

**Comment by acordonez** [comment]
@lee1043 I pushed the notebook

**Review by lee1043 — APPROVED** [review]

**Pull request merged**
