### PR TITLE
Upgrade Taylor Diagram function

### PR DESCRIPTION
**Pull request by lee1043**
* More flexibility (e.g., colormap)
* New capability: Show arrow to compare pair of models

### CODE REVIEW

**Comment by lee1043** [comment]
@acordonez could you please help on verifying this PR by rerunning update notebooks and see if they are reproducible from your end?

**Comment by acordonez** [comment]
@lee1043 Yes I can do this today.

**Review by acordonez — APPROVED** [review]
Looks nice! All ran smoothly on my end.

**Comment by lee1043** [comment]
@acordonez thanks!

**Pull request merged**
