### PR TITLE
Numpy version update

### PR DESCRIPTION
**Pull request by lee1043**
This is one of steps toward xCDAT migration from CDAT. 

`numpy` version has been fixed as `1.23.5` because of conflict with CDAT. Patch of CDAT particular for this conflict was made, which will work with `numpy >= 2.0` that is considered for the next version of E3SM Unified environment. 

PMP's step toward entire migration:
1. Update the `numpy` dependency and make sure it won't break anything. 
2. Remove CDAT dependency.

This PR is for the above step 1. 

Demo notebook run check:
- [x] 0 download
- [x] 1a clim
- [x] 1b clim metrics
- [x] 2a monsoon wang
- [x] 2b monsoon sperber
- [x] 3 diurnal cycle
- [x] 4 MoV
- [x] 5 MJO
- [x] 6 ENSO
- [x] 7 precip variability
- [x] 8 extreme
- [x] 9 sea ice extent
- [x] 9b sea ice data explore

### CODE REVIEW

**Comment by lee1043** [comment]
Conflict with xcdat: https://github.com/xCDAT/xcdat/blob/96bc649ad59750ec37b959d9d4890891b54c62c7/conda-env/dev.yml#L14. @tomvothecoder do we have any plan to update numpy version dependency of xcdat?

**Comment by tomvothecoder** [comment]
Just replied [here](https://github.com/E3SM-Project/e3sm-unified/pull/118#issuecomment-2445399295), yes I will remove the `numpy <2.0.0` constraint soon.

**Comment by lee1043** [comment]
> Just replied [here](https://github.com/E3SM-Project/e3sm-unified/pull/118#issuecomment-2445399295), yes I will remove the `numpy <2.0.0` constraint soon.

Good to know, thank you!

**Comment by tomvothecoder** [comment]
@lee1043 I will release xCDAT v0.7.3 with the new numpy constraints (same as this [PR](https://github.com/xCDAT/xcdat/pull/711)) next week.

**Comment by lee1043** [comment]
xcdat v0.7.3 released: https://github.com/xCDAT/xcdat/releases/tag/v0.7.3

**Comment by tomvothecoder** [comment]
xcdat v0.7.3 is now available on `conda-forge`: https://anaconda.org/conda-forge/xcdat

**Comment by lee1043** [comment]
Now I can create conda env from dev.yml without any conflict
```
conda env create -n pmp_devel_20241106_xcdat0.7.3 -f conda-env/dev.yml
```
```
/Users/lee1043/mambaforge/lib/python3.10/argparse.py:1936: FutureWarning: `remote_definition` is deprecated and will be removed in 25.9. Use `conda env create --file=URL` instead.
  action(self, namespace, argument_values, option_string)
Channels:
 - conda-forge
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:
                                                                                                                                                                                                                     
Preparing transaction: done                                                                                                                                                                                          
Verifying transaction: done                                                                                                                                                                                          
Executing transaction: - Enabling nb_conda_kernels...                                                                                                                                                                
CONDA_PREFIX: /Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3                                                                                                                                           
Status: enabled                                                                                                                                                                                                      
                                                                                                                                                                                                                     
| Enabling notebook extension nb_conda/main...                                                                                                                                                                       
      - Validating: OK                                                                                                                                                                                               
Enabling tree extension nb_conda/tree...                                                                                                                                                                             
      - Validating: OK                                                                                                                                                                                               
Enabling: nb_conda                                                                                                                                                                                                   
- Writing config: /Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/etc/jupyter                                                                                                                           
    - Validating...                                                                                                                                                                                                  
      nb_conda 2.2.1 OK                                                                                                                                                                                              
                                                                                                                                                                                                                     
done                                                                                                                                                                                                                 
#                                                                                                                                                                                                                    
# To activate this environment, use                                                                                                                                                                                  
#                                                                                                                                                                                                                    
#     $ conda activate pmp_devel_20241106_xcdat0.7.3                                                                                                                                                                 
#                                                                                                                                                                                                                    
# To deactivate an active environment, use                                                                                                                                                                           
#
#     $ conda deactivate
```

**Comment by lee1043** [comment]
Error from Demo 1a notebook:

```
%%bash
pcmdi_compute_climatologies.py -p basic_annual_cycle_param.py
```
Error message:
```
start and end are  2003-01   2018-12
variable list:  ['rlut']
ver: v20241023
var: rlut
infile: demo_data_tmp/obs4MIPs_PCMDI_monthly/NASA-LaRC/CERES-EBAF-4-1/mon/rlut/gn/v20210727/rlut_mon_CERES-EBAF-4-1_PCMDI_gn_200301-201812.nc
outfile: demo_output_tmp/climo/rlut_mon_CERES-EBAF-4-1_BE_gn.nc
outfilename: rlut_mon_CERES-EBAF-4-1_BE_gn.nc
outpath: demo_output_tmp/climo/
ver: v20241023
infilename: rlut_mon_CERES-EBAF-4-1_PCMDI_gn_200301-201812.nc
type(d): <class 'xarray.core.dataset.Dataset'>
atts: {'Conventions': 'CF-1.7 ODS-2.1', 'activity_id': 'obs4MIPs', 'contact': 'PCMDI (pcmdi-metrics@llnl.gov)', 'creation_date': '2021-07-27T18:20:26Z', 'curation_provenance': 'work-in-progress', 'data_specs_version': '2.1.0', 'external_variables': 'areacella', 'frequency': 'mon', 'further_info_url': 'https://furtherinfo.es-doc.org/CMIP6.NASA-LaRC.CERES-EBAF-4-1.experiment_idsub_experiment_idPCMDI', 'grid': '1x1 degree latitude x longitude', 'grid_label': 'gn', 'history': '2021-07-27T18:20:26Z; CMOR rewrote data to be consistent with obs4MIPs, and CF-1.7 ODS-2.1 standards', 'institution': 'NASA-LaRC (Langley Research Center) Hampton, Va', 'institution_id': 'NASA-LaRC', 'mip_era': 'CMIP6', 'nominal_resolution': '100 km', 'product': 'observations', 'realm': 'atmos', 'release_year': '2019', 'source': 'CERES EBAF (Energy Balanced and Filled) TOA Fluxes. Monthly Averages', 'source_description': 'CERES EBAF (Energy Balanced and Filled) TOA Fluxes. Monthly Averages', 'source_id': 'CERES-EBAF-4-1', 'source_label': 'CERES-EBAF-4-1', 'source_name': 'CERES-EBAF4-1', 'source_type': 'satellite_blended', 'source_version_number': '4.1', 'table_id': 'obs4MIPs_Amon', 'table_info': 'Creation Date:(18 November 2020) MD5:d8a4a72de798e86a999881bdaeb1809e', 'title': 'CERES prepared for obs4MIPs (ODS-v2.1.0)', 'tracking_id': 'hdl:21.14102/d1afa116-4801-4801-b302-43c49b5bb7dc', 'variable_id': 'rlut', 'variant_info': 'Best Estimate', 'variant_label': 'PCMDI', 'license': 'Data in this file processed for obs4MIPs by PCMDI and is for research purposes only.', 'cmor_version': '3.6.1'}
outdir: demo_output_tmp/climo/
start_yr_str is  2003
start_mo_str is  01
end_yr_str is  2018
end_mo_str is  12
[/Users/lee1043/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/indexing.py:1593](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/indexing.py:1593): PerformanceWarning: Slicing with an out-of-order index is generating 16 times more chunks
  return self.array[key]
[/Users/lee1043/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/indexing.py:1593](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/indexing.py:1593): PerformanceWarning: Slicing with an out-of-order index is generating 16 times more chunks
  return self.array[key]
output file is demo_output_tmp/climo/rlut_mon_CERES-EBAF-4-1_BE_gn.200301-201812.AC.v20241023.nc
output file is demo_output_tmp/climo/rlut_mon_CERES-EBAF-4-1_BE_gn.200301-201812.DJF.v20241023.nc
output file is demo_output_tmp/climo/rlut_mon_CERES-EBAF-4-1_BE_gn.200301-201812.MAM.v20241023.nc
output file is demo_output_tmp/climo/rlut_mon_CERES-EBAF-4-1_BE_gn.200301-201812.JJA.v20241023.nc
output file is demo_output_tmp/climo/rlut_mon_CERES-EBAF-4-1_BE_gn.200301-201812.SON.v20241023.nc
start and end are  2003-01   2018-12
variable list:  ['rlut']
ver: v20241023
[/Users/lee1043/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/pcmdi_metrics/io/string_constructor.py:43](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/pcmdi_metrics/io/string_constructor.py:43): UserWarning: Keyword 'variable' not provided for filling the template.
  warnings.warn(f"Keyword '{k}' not provided for filling the template.")
var: rlut
infile: demo_data_tmp/obs4MIPs_PCMDI_monthly/NASA-LaRC/CERES-EBAF-4-1/mon/rlut/gn/v20210727/rlut_mon_CERES-EBAF-4-1_PCMDI_gn_200301-201812.nc
outfile: demo_output_tmp/climo/rlut_mon_CERES-EBAF-4-1_BE_gn.nc
outfilename: None
outpath: None
ver: v20241023
infilename: rlut_mon_CERES-EBAF-4-1_PCMDI_gn_200301-201812.nc
type(d): <class 'xarray.core.dataset.Dataset'>
atts: {'Conventions': 'CF-1.7 ODS-2.1', 'activity_id': 'obs4MIPs', 'contact': 'PCMDI (pcmdi-metrics@llnl.gov)', 'creation_date': '2021-07-27T18:20:26Z', 'curation_provenance': 'work-in-progress', 'data_specs_version': '2.1.0', 'external_variables': 'areacella', 'frequency': 'mon', 'further_info_url': 'https://furtherinfo.es-doc.org/CMIP6.NASA-LaRC.CERES-EBAF-4-1.experiment_idsub_experiment_idPCMDI', 'grid': '1x1 degree latitude x longitude', 'grid_label': 'gn', 'history': '2021-07-27T18:20:26Z; CMOR rewrote data to be consistent with obs4MIPs, and CF-1.7 ODS-2.1 standards', 'institution': 'NASA-LaRC (Langley Research Center) Hampton, Va', 'institution_id': 'NASA-LaRC', 'mip_era': 'CMIP6', 'nominal_resolution': '100 km', 'product': 'observations', 'realm': 'atmos', 'release_year': '2019', 'source': 'CERES EBAF (Energy Balanced and Filled) TOA Fluxes. Monthly Averages', 'source_description': 'CERES EBAF (Energy Balanced and Filled) TOA Fluxes. Monthly Averages', 'source_id': 'CERES-EBAF-4-1', 'source_label': 'CERES-EBAF-4-1', 'source_name': 'CERES-EBAF4-1', 'source_type': 'satellite_blended', 'source_version_number': '4.1', 'table_id': 'obs4MIPs_Amon', 'table_info': 'Creation Date:(18 November 2020) MD5:d8a4a72de798e86a999881bdaeb1809e', 'title': 'CERES prepared for obs4MIPs (ODS-v2.1.0)', 'tracking_id': 'hdl:21.14102/d1afa116-4801-4801-b302-43c49b5bb7dc', 'variable_id': 'rlut', 'variant_info': 'Best Estimate', 'variant_label': 'PCMDI', 'license': 'Data in this file processed for obs4MIPs by PCMDI and is for research purposes only.', 'cmor_version': '3.6.1'}
outdir: demo_output_tmp/climo
start_yr_str is  2003
start_mo_str is  01
end_yr_str is  2018
end_mo_str is  12
[/Users/lee1043/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/indexing.py:1593](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/indexing.py:1593): PerformanceWarning: Slicing with an out-of-order index is generating 16 times more chunks
  return self.array[key]
[/Users/lee1043/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/indexing.py:1593](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/indexing.py:1593): PerformanceWarning: Slicing with an out-of-order index is generating 16 times more chunks
  return self.array[key]
output file is demo_output_tmp/climo/rlut_mon_CERES-EBAF-4-1_BE_gn.200301-201812.AC.v20241023.nc
output file is demo_output_tmp/climo/rlut_mon_CERES-EBAF-4-1_BE_gn.200301-201812.DJF.v20241023.nc
output file is demo_output_tmp/climo/rlut_mon_CERES-EBAF-4-1_BE_gn.200301-201812.MAM.v20241023.nc
output file is demo_output_tmp/climo/rlut_mon_CERES-EBAF-4-1_BE_gn.200301-201812.JJA.v20241023.nc
output file is demo_output_tmp/climo/rlut_mon_CERES-EBAF-4-1_BE_gn.200301-201812.SON.v20241023.nc
Fontconfig warning: ignoring UTF-8: not a valid region tag
2024-11-06 14:51:21,277 [WARNING]: font_manager.py(<lambda>:1040) >> Matplotlib is building the font cache; this may take a moment.
2024-11-06 14:51:21,277 [WARNING]: font_manager.py(<lambda>:1040) >> Matplotlib is building the font cache; this may take a moment.
2024-11-06 14:51:47,580 [INFO]: font_manager.py(__init__:1052) >> Failed to extract font properties from [/System/Library/Fonts/LastResort.otf](https://file+.vscode-resource.vscode-cdn.net/System/Library/Fonts/LastResort.otf): tuple indices must be integers or slices, not str
2024-11-06 14:51:47,580 [INFO]: font_manager.py(__init__:1052) >> Failed to extract font properties from [/System/Library/Fonts/LastResort.otf](https://file+.vscode-resource.vscode-cdn.net/System/Library/Fonts/LastResort.otf): tuple indices must be integers or slices, not str
2024-11-06 14:51:48,028 [INFO]: font_manager.py(__init__:1052) >> Failed to extract font properties from [/System/Library/PrivateFrameworks/FontServices.framework/Resources/Reserved/PingFangUI.ttc](https://file+.vscode-resource.vscode-cdn.net/System/Library/PrivateFrameworks/FontServices.framework/Resources/Reserved/PingFangUI.ttc): In FT2Font: Can not load face (locations (loca) table missing; error code 0x90)
2024-11-06 14:51:48,028 [INFO]: font_manager.py(__init__:1052) >> Failed to extract font properties from [/System/Library/PrivateFrameworks/FontServices.framework/Resources/Reserved/PingFangUI.ttc](https://file+.vscode-resource.vscode-cdn.net/System/Library/PrivateFrameworks/FontServices.framework/Resources/Reserved/PingFangUI.ttc): In FT2Font: Can not load face (locations (loca) table missing; error code 0x90)
2024-11-06 14:51:48,095 [INFO]: font_manager.py(__init__:1052) >> Failed to extract font properties from [/System/Library/Fonts/Supplemental/NISC18030.ttf](https://file+.vscode-resource.vscode-cdn.net/System/Library/Fonts/Supplemental/NISC18030.ttf): In FT2Font: Could not set the fontsize (invalid pixel size; error code 0x17)
2024-11-06 14:51:48,095 [INFO]: font_manager.py(__init__:1052) >> Failed to extract font properties from [/System/Library/Fonts/Supplemental/NISC18030.ttf](https://file+.vscode-resource.vscode-cdn.net/System/Library/Fonts/Supplemental/NISC18030.ttf): In FT2Font: Could not set the fontsize (invalid pixel size; error code 0x17)
2024-11-06 14:51:48,221 [INFO]: font_manager.py(__init__:1052) >> Failed to extract font properties from [/System/Library/Fonts/Apple](https://file+.vscode-resource.vscode-cdn.net/System/Library/Fonts/Apple) Color Emoji.ttc: In FT2Font: Could not set the fontsize (invalid pixel size; error code 0x17)
2024-11-06 14:51:48,221 [INFO]: font_manager.py(__init__:1052) >> Failed to extract font properties from [/System/Library/Fonts/Apple](https://file+.vscode-resource.vscode-cdn.net/System/Library/Fonts/Apple) Color Emoji.ttc: In FT2Font: Could not set the fontsize (invalid pixel size; error code 0x17)
2024-11-06 14:51:48,270 [INFO]: font_manager.py(_load_fontmanager:1584) >> generated new fontManager
2024-11-06 14:51:48,270 [INFO]: font_manager.py(_load_fontmanager:1584) >> generated new fontManager
Traceback (most recent call last):
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/bin/pcmdi_compute_climatologies.py", line 6, in <module>
    from pcmdi_metrics.mean_climate.lib import calculate_climatology
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/pcmdi_metrics/mean_climate/lib/__init__.py", line 21, in <module>
    from .create_mean_climate_parser import create_mean_climate_parser  # noqa
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/pcmdi_metrics/mean_climate/lib/create_mean_climate_parser.py", line 4, in <module>
    from pcmdi_metrics.mean_climate.lib import pmp_parser
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/pcmdi_metrics/mean_climate/lib/pmp_parser.py", line 6, in <module>
    from pcmdi_metrics.mean_climate.lib.pmp_parameter import (
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/pcmdi_metrics/mean_climate/lib/pmp_parameter.py", line 7, in <module>
    from pcmdi_metrics.utils import StringConstructor
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/pcmdi_metrics/utils/__init__.py", line 20, in <module>
    from .land_sea_mask import apply_landmask, apply_oceanmask, create_land_sea_mask
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/pcmdi_metrics/utils/land_sea_mask.py", line 9, in <module>
    import regionmask
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/regionmask/__init__.py", line 7, in <module>
    from . import core, defined_regions
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/regionmask/defined_regions/__init__.py", line 3, in <module>
    from . import _natural_earth, _ressources
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/regionmask/defined_regions/_natural_earth.py", line 12, in <module>
    from ..core.regions import Regions
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/regionmask/core/regions.py", line 15, in <module>
    from .mask import _inject_mask_docstring, _mask_2D, _mask_3D
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/regionmask/core/mask.py", line 420, in <module>
    mask, lon, lat, polygons, numbers, fill=np.NaN, is_unstructured=False
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.. Did you mean: 'nan'?
```

**Comment by lee1043** [comment]
Demo notebook run check
- [ ] 0 download
- [ ] 1a clim
- [ ] 1b clim metrics
- [ ] 2a monsoon wang
- [ ] 2b monsoon sperber
- [ ] 3a diurnal cycle
- [ ] 4 MoV
- [ ] 5 MJO
- [ ] 6 ENSO
- [ ] 7 precip variability
- [ ] 8 extreme
- [ ] 9 sea ice extent
- [ ] 9b sea ice data explore

**Comment by lee1043** [comment]
Error from MoV

```
%%bash
variability_modes_driver.py -p basic_mov_param.py --case_id "mov_1"
```

```
mip: cmip5
exp: historical
fq: mo
realm: atm
EofScaling: False
RmDomainMean: True
LandMask: False
nc_out_obs, plot_obs: True True
nc_out_model, plot_model: True True
CMEC:False
mode: NAM
seasons: ['DJF']
models: ['ACCESS1-0']
number of models: 1
realization:  r1i1p1
eofn_obs: 1
eofn_mod: 1
parallel: False
output directories:
graphics : demo_output_tmp/mov_1
diagnostic_results : demo_output_tmp/mov_1
metrics_results : demo_output_tmp/mov_1
Converting units by  divide 100.0
Traceback (most recent call last):
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/bin/variability_modes_driver.py", line 411, in <module>
    ) = eof_analysis_get_variance_mode(
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/pcmdi_metrics/variability_mode/lib/eof_analysis.py", line 64, in eof_analysis_get_variance_mode
    solver = Eof(da, weights=area_weights)
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/eofs/xarray.py", line 130, in __init__
    self._solver = standard.Eof(array.data,
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/eofs/standard.py", line 124, in __init__
    channels = np.product(self._originalshape)
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/numpy/__init__.py", line 410, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'product'
```

**Comment by lee1043** [comment]
Error from MJO:
```
%%bash
mjo_metrics_driver.py -p basic_mjo_param.py
```

```
includeOBS: True
models: ['GISS-E2-H']
realization:  r6i1p1
output directories:
graphics : demo_output_tmp/mjo/Ex1
diagnostic_results : demo_output_tmp/mjo/Ex1
metrics_results : demo_output_tmp/mjo/Ex1
CMEC: False
debug:  False
parallel: False
 -----  obs  ---------------------
 ---  GPCP-IP  ---
demo_data_tmp/obs4MIPs_PCMDI_daily/NASA-JPL/GPCP-1-3/day/pr/gn/latest/pr_day_GPCP-1-3_PCMDI_gn_19961002-20170101.nc
 --  NDJFMA  --
1998
Converting units by  multiply 86400.0
warning: failed for  obs GPCP-IP module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
 -----  GISS-E2-H  ---------------------
 ---  r6i1p1  ---
demo_data_tmp/CMIP5_demo_timeseries/historical/atmos/day/pr/pr_day_GISS-E2-H_historical_r6i1p1_20000101-20051231.nc
 --  NDJFMA  --
2000
Converting units by  multiply 86400.0
2001
Converting units by  multiply 86400.0
warning: failed for  GISS-E2-H r6i1p1 module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by lee1043** [comment]
Error from ENSO:
```
%%bash
enso_driver.py --help
```
```
Traceback (most recent call last):
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/bin/enso_driver.py", line 16, in <module>
    from EnsoMetrics.EnsoCollectionsLib import (
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/EnsoMetrics/__init__.py", line 2, in <module>
    from .EnsoComputeMetricsLib import *
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/EnsoMetrics/EnsoComputeMetricsLib.py", line 11, in <module>
    from .EnsoMetricsLib import BiasPrLatRmse, BiasPrLonRmse, BiasPrRmse, BiasSshLatRmse, BiasSshLonRmse, BiasSshRmse,\
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/EnsoMetrics/EnsoMetricsLib.py", line 12, in <module>
    from .EnsoUvcdatToolsLib import ArrayListAx, ArrayToList, AverageMeridional, AverageZonal, BasinMask, CheckTime,\
  File "/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/EnsoMetrics/EnsoUvcdatToolsLib.py", line 14, in <module>
    from numpy import product as NPproduct
ImportError: cannot import name 'product' from 'numpy' (/Users/lee1043/mambaforge/envs/pmp_devel_20241106_xcdat0.7.3/lib/python3.10/site-packages/numpy/__init__.py)
```

**Comment by lee1043** [comment]
Error from Demo 7 precip variavbilitiy
```
%%bash -s "$demo_output_directory"
variability_across_timescales_PS_driver.py -p basic_precip_variability_param.py \
--region_file $1/shp/CONUS.shp \
--attr 'Region' \
--feature 'CONUS' \
--results_dir $1/precip_variability/region_ex
```
Error message:
```
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?c9ec7769-567c-4614-ae79-06a086fe1c01) or open in a [text editor](command:workbench.action.openLargeOutput?c9ec7769-567c-4614-ae79-06a086fe1c01). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
demo_data_tmp/CMIP5_demo_timeseries/historical/atmos/day/pr/
pr_day_GISS-E2-H_historical_r6i1p1_*.nc
[2000, 2005]
730 365
2
demo_output/precip_variability/region_ex
demo_output/precip_variability/region_ex
demo_output/precip_variability/region_ex
['demo_data_tmp/CMIP5_demo_timeseries/historical/atmos/day/pr/pr_day_GISS-E2-H_historical_r6i1p1_20000101-20051231.nc']
GISS-E2-H.r6i1p1
['demo_data_tmp/CMIP5_demo_timeseries/historical/atmos/day/pr/pr_day_GISS-E2-H_historical_r6i1p1_20000101-20051231.nc']
GISS-E2-H.r6i1p1 365_day
2000 2005
Complete regridding from (2190, 90, 144) to (2190, 90, 180)
Cropping from shapefile
Reading region from file.
bash: line 5: 84435 Segmentation fault: 11  variability_across_timescales_PS_driver.py -p basic_precip_variability_param.py --region_file $1/shp/CONUS.shp --attr 'Region' --feature 'CONUS' --results_dir $1/precip_variability/region_ex
```

**Comment by lee1043** [comment]
Error from Demo 8:
```
%%bash
extremes_driver.py  -p basic_extremes_param.py
```

This does not generate the output directory `extremes_1`

**Comment by lee1043** [comment]
Not surprisingly, bunch of errors raised from demo notebooks, likely resulted from the numpy version update. Demo notebooks 0 to 3 run okay, but others are failing. 

@acordonez I will work on notebooks 4 to 6, and can I get you help on notebooks 7 to 9? Just a reminder, to test these, it is needed to generate a new conda env using the dev.yml in this branch.

**Comment by lee1043** [comment]
Regarding the error with ENSO: https://github.com/CLIVAR-PRP/ENSO_metrics/pull/80

**Comment by acordonez** [comment]
@lee1043 I found an unrelated bug in Demo 8 but otherwise it runs without issue. Did you have any issues with Demo 8?

**Comment by lee1043** [comment]
> @lee1043 I found an unrelated bug in Demo 8 but otherwise it runs without issue. Did you have any issues with Demo 8?

Thank you for investigating. I had an issue with Demo 8 as in https://github.com/PCMDI/pcmdi_metrics/pull/1164#issuecomment-2461154759 that it does not generate the output directory, but didn't get a chance to dive in deep to found the cause.

**Comment by acordonez** [comment]
@lee1043 Thanks for pointing that out! I'm not able to reproduce that issue in this branch so it might not be related to numpy at least.

**Comment by lee1043** [comment]
> @lee1043 Thanks for pointing that out! I'm not able to reproduce that issue in this branch so it might not be related to numpy at least.

Interesting because mine was not numpy-related neiter. I manually removed the output directory of demo 8 before starting it to make sure new files to be generated, and noticed that it does not make the output directory. Could you double check if this error does not occur on your end?

**Comment by acordonez** [comment]
@lee1043 Yes, I don't have this problem on my end with Demo 8. It creates all the output directories even when the demo_output folder did not exist at runtime.

**Comment by acordonez** [comment]
In the precip variability metrics, faulthandler flagged this line as causing the segmentation fault: https://github.com/PCMDI/pcmdi_metrics/blob/main/pcmdi_metrics/precip_variability/lib/lib_variability_across_timescales.py#L306
I've attached the whole error trace.
Weirdly, if I put a `print(expanded)` at line 305, the segmentation fault does not happen. 
[pythonerror.txt](https://github.com/user-attachments/files/17707060/pythonerror.txt)

**Comment by lee1043** [comment]
Regarding MoV, `eofs` v2.0.0 is now released which solved the conflict with newer `numpy` versions.

**Comment by lee1043** [comment]
Confirmed now demo 6 ENSO notebook working without issues after updating enso_metrics version to 1.1.2.

**Comment by lee1043** [comment]
Confirmed MoV notebook also working after updating eofs to 2.0.0.

**Comment by acordonez** [comment]
@lee1043 I didn't find any problems with notebooks 8, 9, or 9b. In the comment above I documented some of the experimentation I did with the precip variability metrics and have one suggestion for a workaround.

**Comment by lee1043** [comment]
@acordonez thanks for the update. Great to hear there were no issue with 8, 9, and 9b. What do you consider as the most efficient and quick solution for the issue with 7?

By the way, I found that CI build test was failing with the following message. Have you seen something like this? I am yet to have good idea how to address it.
```
Updating 'pcmdi_metrics_ci' env from conda env update...
  /home/runner/miniconda3/condabin/mamba env create --name pcmdi_metrics_ci --file conda-env/ci.yml
  Warning: /home/runner/miniconda3/lib/python3.12/argparse.py:2006: FutureWarning: `remote_definition` is deprecated and will be removed in 25.9. Use `conda env create --file=URL` instead.
    action(self, namespace, argument_values, option_string)
  
  /home/runner/miniconda3/lib/python3.12/argparse.py:2006: FutureWarning: `remote_definition` is deprecated and will be removed in 25.9. Use `conda env create --file=URL` instead.
    action(self, namespace, argument_values, option_string)
  Channels:
   - conda-forge
   - defaults
  Platform: linux-64
  Collecting package metadata (repodata.json): ...working... done
  Solving environment: ...working... ::warning::warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0Awarning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY%0A
  warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
  ```

**Comment by acordonez** [comment]
@lee1043 For the precip variability metrics, this is the solution I found that worked in all cases:
Change [Line 86](https://github.com/PCMDI/pcmdi_metrics/blob/main/pcmdi_metrics/precip_variability/lib/lib_variability_across_timescales.py#L86) to `rgtmp = RegridHoriz(f.compute(), var, res, regions_specs, lon_range)`.

I'm not sure about the conda build failure. It seems like it might be having difficulty solving the environment and either failing or timing out as a result?

**Comment by lee1043** [comment]
@acordonez thank you for the suggestion. I will make that change to this PR. I think the above changes in the yml files helped passing the test. In summary, I fixed some versions of dependencies, and set conda channel to be flexible, and set to use conda classic solver.

**Comment by lee1043** [comment]
Confirmed demo 7 working with no noticeable issue.

**Comment by lee1043** [comment]
Merging the PR after reviewed by @lee1043 and @acordonez and all CI tests passed.

**Pull request merged**
