### PR TITLE
Turn off github action for draft PRs

### PR DESCRIPTION
**Pull request by lee1043**
Followed solution from https://github.com/orgs/community/discussions/25722#discussioncomment-3248917

### CODE REVIEW

**Comment by lee1043** [comment]
@tomvothecoder when you have time, would you be able to help reviewing this? I am trying to turn off github action when PR is draft mode.

**Review by tomvothecoder — APPROVED** [review]
You can check if the build is correctly ignored by marking this PR as draft. Afterwards, you can mark it as "Ready for Review" to see if it runs. 

The code changes seem correct to me.

**Comment by lee1043** [comment]
@tomvothecoder thank you for the great advice! That was very helpful!

**Comment by lee1043** [comment]
Relevant discussion: https://github.com/orgs/community/discussions/25722

**Pull request merged**
