### PR TITLE
Remove vcs dependency

### PR DESCRIPTION
**Pull request by lee1043**

### CODE REVIEW

**Review by lee1043 — COMMENTED** [review]
@tomvothecoder would you mind taking a quick look if I made [this change](https://github.com/PCMDI/pcmdi_metrics/pull/786/commits/acd0b87c865e79902a72fb189dbee6d0f3d19efe) properly? I wanted to add another directory where legacy code stored to be excluded from whatever test..

**Comment by tomvothecoder** [comment]
@lee1043 That looks good to me. I would try activating the dev env and running the command `pytest` to see if it properly ignores the directory. The files should not appear in the coverage report console output.

**Comment by lee1043** [comment]
Removing `mypy` sounds reasonable at this moment because most of PMP code has been wrote with dynamic typing, instead of static typing as checked by `mypy`.

**Comment by lee1043** [comment]
Closed this PR to start with latest codes that are pre-commit compliant as result of PR https://github.com/PCMDI/pcmdi_metrics/pull/793.

**Pull request closed without merging**
