### PR TITLE
343 pjg simple demos

### PR DESCRIPTION
**Pull request by gleckler1**
@doutriaux1 @durack1  Changes to setup.py have been made as discussed,  but likely need work.   Demo data is currently not built into package but rather available at http://oceanonly.llnl.gov/gleckler1/pmp-demo-data/pmpv1.1_demodata.tar as indicated in demo1 parameter file:
https://github.com/PCMDI/pcmdi_metrics/blob/343_pjg_simple_demos/demo/parameter_files/pmp_input_parameters_demo1.py

PLS address ASAP so that we can iterate as needed and because there is more "demo" coming.

FYI documentation progressing: https://github.com/PCMDI/pcmdi_metrics/wiki/Using-the-package

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 there are still errors in travis, so will leave this for you to resolve..

**Comment by durack1** [comment]
@doutriaux1 this is still causing segfaults:
 [here](https://travis-ci.org/PCMDI/pcmdi_metrics/builds/144222459#L2102) and [here](https://travis-ci.org/PCMDI/pcmdi_metrics/builds/144219663)
`/Users/travis/build.sh: line 45:  1761 Segmentation fault: 11  python test/test_suite.py`

**Comment by gleckler1** [comment]
@doutriaux1 @durack1  Really need to get this fixed/pushed asap.... 2 users struggling with demo right now and need this.

**Comment by durack1** [comment]
@gleckler1 this is still going to fail the tests until the fixes in #378 are merged into `master` and these changes are pulled into this branch.. If it's holding you up, merge this, however it's going to cause conflicts with the `setup.py` edits in #378

**Comment by gleckler1** [comment]
@durack1 @doutriaux1  Agreed, best would be get it all in, but first the bug in #378 (failing with needs to be fixed, and also verify that PG has not messed setup with this (PR343)

**Comment by durack1** [comment]
@gleckler1 if you feel like a pro, you could merge #378 into this branch and push again.. Then we'd know and could merge without hesitation..

**Comment by gleckler1** [comment]
@durack1 not a pro

**Comment by durack1** [comment]
@gleckler1 wanna be a pro?

`git fetch --all -p` ; # Will pull all remote history across to your repo, without changing anything
`git merge --no-commit origin/issue_316_regions` ; # A dry run to see what will change

and if you like what you see

`git merge --no-ff origin/issue_316_regions` ; # Make the changes

I think.. You'll likely also have to fix the `setup.py` conflicts..

**Comment by gleckler1** [comment]
@durack1 don't want to be a pro... I'm juggling too many fires to do this well... what I'm looking for is help

**Comment by durack1** [comment]
@gleckler1 I tried with #379 but I am no out-pro'd, so will have to wait for @doutriaux1 to take a peek

**Comment by doutriaux1** [comment]
hum @gleckler1 did you really mean to close this?

**Comment by doutriaux1** [comment]
oh i see you have another issue #371

**Comment by gleckler1** [comment]
@doutriaux1 yes its nearly the same as 
https://github.com/PCMDI/pcmdi_metrics/pull/376...
checking out til 9am

**Comment by gleckler1** [comment]
@doutriaux1 scratch that, have kept this open and instead closed 
https://github.com/PCMDI/pcmdi_metrics/pull/373
PLEASE REVIEW AND MODIFY AS NECESSARY.  NEED FEEDBACK ON proposed setup changes before preparation of demos can be continued

**Comment by doutriaux1** [comment]
@gleckler1 why did you merge?

**Comment by gleckler1** [comment]
@doutriaux1 Because I've been pleading for this to be the top priority since it was opened and kept asking for it to be looked at and nothing was happening.   As noted the priority was to help me advance the other demo stuff coming down z pipe ...

**Comment by doutriaux1** [comment]
yes but there are things to tweak. I reverted it and will resubmit the PR soon. Look at my comments please

**Comment by doutriaux1** [comment]
why did you need it into master? If you need this for something else, simply merge this branch into whatever branch needs it.

**Comment by gleckler1** [comment]
I wanted to get your confirmation on how the demo files were going to get mapped by setup.py (and into conda build) so that I could advance other demos based on their location.

**Pull request merged**
