### PR TITLE
Precip variability across time scales

### PR DESCRIPTION
**Pull request by lee1043**
I am opening PR for the precip variabliity metric. @msahn, do you consider the branch is ready to be merged?

### CODE REVIEW

**Comment by lee1043** [comment]
@msahn I don't think demo notebook is included in this branch. I can not recall if we had one or not, could you please remind me?

**Comment by msahn** [comment]
> @msahn I don't think demo notebook is included in this branch. I can not recall if we had one or not, could you please remind me?

Ana created the demo notebook for the precip variability at the branch below.
https://github.com/PCMDI/pcmdi_metrics/tree/731_ao_precip_benchmark_nb

**Comment by msahn** [comment]
> I am opening PR for the precip variabliity metric. @msahn, do you consider the branch is ready to be merged?

Thank you. I think this branch will be ready after merging the branch you made for modifying code style.

**Comment by lee1043** [comment]
> > @msahn I don't think demo notebook is included in this branch. I can not recall if we had one or not, could you please remind me?
> 
> Ana created the demo notebook for the precip variability at the branch below. https://github.com/PCMDI/pcmdi_metrics/tree/731_ao_precip_benchmark_nb

@acordonez I am planning to merge this PR to master, but it looks like demo notebook and associated parameter files are in a different [branch](https://github.com/PCMDI/pcmdi_metrics/tree/731_ao_precip_benchmark_nb), which may have branched out from @msahn's other branch for another precip metric. I was looking for merging that branch into this branch for the notebook, but then it will bring the ongoing another precip metric into this branch. What would be the best way to bring your notebook for this PR to the master? Would you be able to pull only notebooks from your branch to this branch (or the `main` branch, whatever works easier to you)?

**Comment by acordonez** [comment]
@lee1043 @msahn The notebook in my 731 branch is for the variability_across_timescales_PS_driver.py and calc_ratio.py scripts, so if those are the right metrics for this branch then yes, that's the notebook. I should be able to pull all the PMP updates into that branch. Once it's updated it could be merged into this branch.

**Comment by lee1043** [comment]
@acordonez thanks for your comment. I see in the `731_ao_precip_benchmark_nb` branch the following directory is included: [`pcmdi_metrics/precip_distribution`](https://github.com/PCMDI/pcmdi_metrics/tree/731_ao_precip_benchmark_nb/pcmdi_metrics/precip_distribution), while this PR is for `pcmdi_metrics/precip_variability`. I think @msahn is still working on the `precip_distribution` metric (please correct me if I am wrong), so I just wanted to make sure avoiding the `precip_distribution` codes to be accidentally merged to main (via this PR) when pulling the `731_ao_precip_benchmark_nb` into this branch for the notebook.

**Comment by acordonez** [comment]
@msahn @lee1043 I opened a PR into this branch (not main) with just the jupyter notebook and parameter file: https://github.com/PCMDI/pcmdi_metrics/pull/823

**Comment by gleckler1** [comment]
@msahn @acordonez @lee1043 precip variability is looking great including demo.  I agree the precip_distribution should not be included in the PR.

**Comment by acordonez** [comment]
@lee1043 @msahn I pulled this branch and tested the notebook, and found a couple of fixes were still needed. Here's the PR with those: https://github.com/PCMDI/pcmdi_metrics/pull/824

**Comment by lee1043** [comment]
@acordonez thank you for the fix!

**Review by acordonez — APPROVED** [review]

**Pull request merged**
