### PR TITLE
384 pjg plot json query

### PR DESCRIPTION
**Pull request by gleckler1**
@doutriaux1   This is garbled with the merged to master that needed to be undone, probably because PG mucked up setup.py.   But the examples that are introduced ....

### CODE REVIEW

**Comment by gleckler1** [comment]
@doutriaux1 pretty garbled... two examples here.. one is read json the other is sample portrait..

**Comment by durack1** [comment]
@gleckler1 it seems you have to merge with master here (two files are conflicting see above) and then this should be good to merge (once the test passes)

**Comment by doutriaux1** [comment]
the basic_portrait.py file should be updated to use the JSON class.

**Comment by durack1** [comment]
@doutriaux1 curious about this one too?

**Pull request closed without merging**
