### PR TITLE
New workflow for xcdat mean climate metrics

### PR DESCRIPTION
**Pull request by lee1043**
In this PR:
* CDAT in mean climate was replaced by xCDAT.
* The mean climate driver was re-written from scratch with using some of existing functions, with substantial re-organization of the directory for mean climate metrics.
* Many of class-based objects that over-complicates code maintenance were deprecated (moved to 'deprecated' directory, and will be removed later).

This PR is intended to replace the previous PR, #884.

### CODE REVIEW

**Comment by lee1043** [comment]
Comparison of metrics obtained from cdms-based and xcdat-based codes for pr global looks promising!

compare_metrics_pr_global

**Comment by lee1043** [comment]
Screen Shot 2023-02-06 at 3 49 41 PM

Test results for CMIP6 models proves great consistency between results from xcdat-based and cdms-based codes.

**Comment by lee1043** [comment]
@acordonez I think this PR is ready for review. When you have a chance, could you take a look and also try run demo notebooks to ensure this change is not breaking the demo?

**Comment by lee1043** [comment]
@gleckler1 once this PR is merged, the capability of getting annual cycle using xcdat is going to be applicable to the obs4mips workflow in more efficient way.

**Review by acordonez — APPROVED** [review]
I tested this PR in Demos 1a and 1b. Both notebooks run completely and produce the expected metric and netcdf files.

**Pull request merged**
