### PR TITLE
attempted redo

### PR DESCRIPTION
**Pull request by gleckler1**

### CODE REVIEW

**Comment by gleckler1** [comment]
@lee1043 @acordonez  In the past when I have had a CI problem with a PR that I did not understand I was able mysteriously make the problem go away just be recreating a new branch and trying again.  Trying that here...

**Comment by lee1043** [comment]
Interesting... let's see what happens here.

**Comment by gleckler1** [comment]
@lee1043 looks like this time it may have made it?

**Comment by lee1043** [comment]
It is strange that only those below three tests are keep failing even after rerunning them.

test-linux-3.6-mpi_mpich
test-linux-3.6-mpi_openmpi
test-linux-3.6-nompi

Which error messages shown in common is 
```
File "/home/circleci/project/workdir/linux/miniconda/envs/test-pcmdi_metrics/lib/python3.6/site-packages/cdms2/cdmsNode.py", line 10, in <module>'
b'    import cdtime'
b'ImportError: libnetcdf.so.11: cannot open shared object file: No such file or directory'
```

I am not clear why that happens but I don't think the failure in the test caused by changes in this PR. Let me merge it to the master for now using the admin privilege.

**Pull request merged**
