### PR TITLE
509 pjg clim departures

### PR DESCRIPTION
**Pull request by gleckler1**
@doutriaux1 @durack1   All intended changes are to mean_climate_metrics_calculations.py 
... not sure what jupyter stuff is coming from... it can be removed before merging if that make sense

### CODE REVIEW

**Comment by gleckler1** [comment]
@doutriaux1 @durack1  I don't understand what checks have failed here.   Can one of you check and merge this so that I can close several issues and build on this?

**Comment by doutriaux1** [comment]
I need to merge master in, and we still have this issue that I need to explore with Denis

C.

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 .... more than a week... we need to be in a mode where simple merges such as this can turn around in less than a day... why are we not there?

**Comment by doutriaux1** [comment]
@gleckler1 why did you add the JsoonClass ipynb in that PR? Why did portrait notebook changed? 
Test suite fails, but that might be due to master that needs to be remerged into this.
took more than a week 'cause I was sick last week and I have one dedicated day per week. Not sure why @durack1 did not review.

**Comment by doutriaux1** [comment]
@gleckler1 master passes test suite, so in theory we shoudln't even start reviewing until test passes. Please merge master into your branch.
Also no branch should be merged w/o  a test for the new feature(s) being added...

**Comment by doutriaux1** [comment]
@gleckler1 do we want this one?

**Comment by gleckler1** [comment]
@doutriaux1 funny you should ask, I was just looking at this yesterday.  The answer for the two file changes is yes.  I don't know what the notebook is - I will take a look at it.

**Comment by doutriaux1** [comment]
@gleckler1 I merged master in this one as well and fixed conflicts.

**Comment by lee1043** [comment]
@gleckler1 in effort of housekeeping, could you please check what's the status of this branch? Is this PR still valid?

**Comment by lee1043** [comment]
@gleckler1 could you remind me if this PR is still valid?

**Comment by lee1043** [comment]
@gleckler1 I guess this PR is inactive and should be okay to close it without merging, is that correct?

**Comment by lee1043** [comment]
@gleckler1 I changed this PR to draft status. It looks like key addition in this PR is to add "rms_devzm_xy","rms_devam_xy" statistics for the mean climate metrics. I will consider adding them to the xcdat version mean climate later.

**Comment by lee1043** [comment]
I am closing this PR and will reopen a new one once it is ready for #897.

**Pull request closed without merging**
