### PR TITLE
Update central arctic domain

### PR DESCRIPTION
**Pull request by acordonez**
This PR expands the central arctic domain to remove the masking for the pole hole. On closer reading of the Ivanova (2016) paper, the pole hole was only masked for the ice edge analysis but not for the total ice area analysis.

### CODE REVIEW

**Comment by acordonez** [comment]
@lee1043 That's correct. The OSI-SAF data we're using does have data over the hole, not sure how that's accomplished.

**Comment by acordonez** [comment]
@lee1043 Also looking at this code we've been including the sea ice data over the pole in the whole Arctic metrics, but not the central arctic metrics. If we do decide to mask the hole then I need to update the total Arctic region.

**Comment by lee1043** [comment]
@acordonez Do you think this exclusion of pole hole can be set as optional capability with a parameter accompanying with?

**Review by lee1043 — APPROVED** [review]

**Comment by lee1043** [comment]
Note: pole option added by #1087 

@acordonez please feel free to merge

**Pull request closed without merging**
