### PR TITLE
fix #229

### LINKED ISSUE #229: Pass the complete variable name to compute_metrics (ua-XXX)
In case we want to use the variable name within a custom compute_metrics function, it would be useful if 'var' was the same as the variable name provided in the parameter file.
The variable name in the output json file name is var-level, when it is var_level in the parameter file.
Would it be beneficial to have the same naming convention everywhere? (i.e. choose between var-level and var_level)

### PR DESCRIPTION
**Pull request by doutriaux1**
passing var to compute funcs the same way the user def it in parameter file, that allows compute to query the level

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 we need to think about this - so level should use "-" rather than "_" as we've standardised on the output files including "_" as the variable delimiters..

**Comment by durack1** [comment]
@doutriaux1 are you happy to standardise this syntax on `"ua-200"` rather than `"ua_200"` as currently?

**Comment by doutriaux1** [comment]
@durack1 let's talk about it with @taylor13 I'm not excited about '-' maybe some other character like '@' ?

**Comment by durack1** [comment]
@doutriaux1 it seems DRS doesn't define this, yet..

http://cmip-pcmdi.llnl.gov/cmip5/docs/cmip5_data_reference_syntax.pdf

**Comment by taylor13** [comment]
Hi Paul and Charles,

Let's talk on Wed.

Welcome home Paul.

cheers,
Karl

**Comment by durack1** [comment]
So @doutriaux1 @taylor13 did we decide that `"ua@200"` was the path forward here.. @taylor13 does that jive with DRS?

**Comment by taylor13** [comment]
I meant to tell you yesterday.  We have CMIP5 variables named wap500 
(pressure velocity at 500 hPa) and ta700 (air temperature at 700 hPa) 
and there might be some others.

For consistency I recommend leaving out the @.  Of course you could 
include the @ in everything *before* you write the variable and at that 
point eliminate it.

Karl

**Comment by doutriaux1** [comment]
@durack1 so.... what did we decide for this?

**Comment by durack1** [comment]
@doutriaux1 good question - I think something parse-able that we can strip out..

**Comment by durack1** [comment]
@doutriaux1 this is also waiting on me I suppose?

**Pull request merged**
