### PR TITLE
Add precip variability and distribution to docs

### PR DESCRIPTION
**Pull request by acordonez**
This is a draft of a page for the precipitation variability metrics on our GitHub.io site.

TODO
- [ ] Squash commits
- [ ] Add overview to precip distribution
- [ ] Add submitted paper to precip distribution as reference?

Address #965

### CODE REVIEW

**Review by lee1043 — APPROVED** [review]

**Comment by lee1043** [comment]
@acordonez this looks good to me, please feel free to merge it.

**Comment by lee1043** [comment]
@acordonez can this be merged?

**Comment by acordonez** [comment]
I'm missing some overview text and a reference for the Precip Distribution page, but if we're fine skipping that for now then I'm ok with merging.

**Comment by lee1043** [comment]
@acordonez thank you for clarifying. I added an overview text, reference paper, and a placeholder for demo for precip distribution.

**Comment by acordonez** [comment]
@lee1043  Thank you for adding those, I'll merge this

**Pull request merged**
