### PR TITLE
Sea ice reference data added to demo 0 downloading

### PR DESCRIPTION
**Pull request by lee1043**
EUMETSAT sea-ice reference data is added to demo 0 download, and note added to Demo 9 notebook

### CODE REVIEW

**Review by acordonez — COMMENTED** [review]
The notebook ran successfully but I was not able to download the files. Instead of netcdf files I get text files with this message. I'll let Peter know.
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /pss/pmpdata/misc_demo_data/ocn/ice_conc_nh_ease2-250_cdr-v3p0_198801-202012.nc
on this server.</p>
</body></html>
```

**Review by acordonez — APPROVED** [review]
The latest permissions update fixed this for me!

**Comment by lee1043** [comment]
@acordonez thank you for checking!

**Comment by lee1043** [comment]
I should have merged this directly to main... oops. I am opening a new PR to update main by merging 405_sic_ao for this change. Sorry for the confusion.

**Pull request merged**
