### PR TITLE
Click

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by gleckler1** [comment]
@doutriaux1 I'll try to take her for a spin tomorrow... is there an example somewhere?

**Comment by lee1043** [comment]
I will also test this as my first thing on upcoming Monday.

**Comment by lee1043** [comment]
@doutriaux1 below is error message I am getting when I tried with this update.
```
Deprecation warning: please use 'import pcmdi_metrics.driver.pmp_parser.PMPParser'
LOOKING AT PATTERN: *.json in ./json_files
We are looking at 5 Json Files:
Traceback (most recent call last):
  File "/export_backup/lee1043/git/click/modal/generate_modal.py", line 167, in <module>
    data = J(**dic)(squeeze=1)
  File "build/bdist.linux-x86_64/egg/pcmdi_metrics/io/base.py", line 645, in __call__
RuntimeError: You requested to merge axis is '['model', 'realization']' which is not valid. Axes: ['variable', u'model', u'realization', u'reference', u'mode', u'season', u'statistic']
```
I don't know why it complains it cannot find `model` and `realization` while they were listed as `Axes`. It may be because of the dictionary key thing, `u`? Any idea?

**Comment by lee1043** [comment]
https://github.com/PCMDI/pcmdi_metrics/blob/607baaeb8c4a7b348bca11ccabe7bee13c04358f/pcmdi_metrics/io/base.py#L645

**Comment by lee1043** [comment]
@doutriaux1 I think I nailed the cause of my error.
```
(Pdb) merge
[['model', 'realization'], ['mode', 'season']]
(Pdb) merger
['model', 'realization']
(Pdb) axes_ids
['variable', u'model', u'realization', u'reference', u'mode', u'season', u'statistic']
(Pdb) merger in axes_ids
False
```
- Is merge always be list of list, including two pairs of axes? or could it be just a list of two axes? If it could be a list of two axes, current code should work. But it seems my case is not. In my parameter, my merger is like following: ```merge = [["model", "realization"], ["mode", "season"]]```, so it is a list of lists.
- I think the error for my case is coming from checking `merger` in `axes_ids` at below linked line of code, rather than checking `merger[0] in axes_ids` or `merger[1] in axes_ids`
https://github.com/PCMDI/pcmdi_metrics/blob/607baaeb8c4a7b348bca11ccabe7bee13c04358f/pcmdi_metrics/io/base.py#L643

**Comment by lee1043** [comment]
Below and attached (please remove .TXT at the end of file name) are a toy code that I wrote to flatten list of lists. Hope this help.

```python
import itertools

def flatten(list0):
    """
    NOTE: Flatten given list of lists to list
    input
    - list0: list, string, list of lists, etc.
    output
    - list2: flat list
    """
    if isinstance(list0, list):
        list1 = [([x] if isinstance(x, str) else x) for x in list0]
        list2 = list(itertools.chain(*list1))
    else:
        list2 = [list0]
    return list2
```

```python
merge1 = [["model", "realization"], ["mode", "season"]]  # WORK
merge2 = ["model", "realization"] # WORK
merge3 = [["model", "realization"], ["mode", "season"], 'test']  # WORK
merge4 = [["realization"], ["mode", "season"], 'test0', ['test1', 'test2']]  # WORK
merge5 = 'model'  # WORK
merge6 = [[['model', 'realization'], ['mode', 'season']], 'test0']  # NOT WORK
print(flatten(merge1))
print(flatten(merge2))
print(flatten(merge3))
print(flatten(merge4))
print(flatten(merge5))
print(flatten(merge6))
```

```
['model', 'realization', 'mode', 'season']
['model', 'realization']
['model', 'realization', 'mode', 'season', 'test']
['realization', 'mode', 'season', 'test0', 'test1', 'test2']
['model']
[['model', 'realization'], ['mode', 'season'], 'test0']
```

[flatten_list_of_list.ipynb.TXT](https://github.com/PCMDI/pcmdi_metrics/files/2944458/flatten_list_of_list.ipynb.TXT)
[flatten_list_of_list.py.TXT](https://github.com/PCMDI/pcmdi_metrics/files/2944459/flatten_list_of_list.py.TXT)
[flatten_list_of_list.html.TXT](https://github.com/PCMDI/pcmdi_metrics/files/2944456/flatten_list_of_list.html.TXT)

**Comment by doutriaux1** [comment]
@lee1043 always a list of list.

**Comment by lee1043** [comment]
@doutriaux1 good to learn, thanks for confirming.

**Pull request merged**
