### PR TITLE
string constructor

### PR DESCRIPTION
**Pull request by lee1043**
`from genutil import StringConstructor` is replaced by `from pcmdi_metrics.utils import StringConstructor`

### CODE REVIEW

**Comment by lee1043** [comment]
[Demo4](https://github.com/PCMDI/pcmdi_metrics/blob/main/doc/jupyter/Demo/Demo_4_modes_of_variability.ipynb) and [Demo5](https://github.com/PCMDI/pcmdi_metrics/blob/main/doc/jupyter/Demo/Demo_5_mjo_metrics.ipynb) (MJO) were checked and they remain identical.

**Comment by lee1043** [comment]
No noticeable error found from all Demo notebooks.

**Comment by lee1043** [comment]
@acordonez Could you please review when you get a chance? I don't think this PR would need line by line review as the change is scattered across many file, but in general, change is for replacing `from genutil import StringConstructor` by `from pcmdi_metrics.utils import StringConstructor`. Please briefly check if this makes sense to you and/or if it is applicable to your extreme branch.

Most of changes in the PR is resulted by hosting the [`StringConstructor`](https://github.com/PCMDI/pcmdi_metrics/blob/ca3cbf4b6f1f1d452bd702f6f220153b56163187/pcmdi_metrics/utils/string_constructor.py) capability in the PMP, which was originated from `genutil` [code](https://github.com/CDAT/genutil/blob/59517ab54e65c03098502f63434270f96020f3eb/Lib/Filler.py#L1).

**Comment by acordonez** [comment]
@lee1043 Yes I'll give it a run on my end!

**Comment by acordonez** [comment]
@lee1043  I ran mean climate and mjo demos and they both finished successfully.

**Review by acordonez — APPROVED** [review]

**Comment by lee1043** [comment]
@acordonez thank you, I am merging this PR.

**Pull request merged**
