### PR TITLE
Issue 220 custom per variable

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
be careful because of mis numbering on my end this will unfortunately close #232 let's check and reopen it if needed after merging this

**Comment by doutriaux1** [comment]
@jservonnat take a look at this PR

**Comment by durack1** [comment]
@jservonnat if you feel like this fixes things then we'll merge this back into the master branch.. Let us know!

**Comment by doutriaux1** [comment]
@durack1 this does not change the code at all, but provides a better example on how to do what @jservonnat needs, so I think you should merge it in either way

**Comment by jservonnat** [comment]
@doutriaux1 @durack1 I'm not really sure it will make the deal... let me a couple of days and I'll give you an official answer. Thanks!

**Comment by durack1** [comment]
@doutriaux1 won't merge until @jservonnat gets back to us on this.. I agree it's just a param file tweak, but may as well get this done properly before merging..

**Comment by doutriaux1** [comment]
@durack1 as you want. Both ways are proper. This one just shows @jservonnat how to achieve what he wants.

**Comment by jservonnat** [comment]
Checked today, that's perfect! You can merge!

**Pull request merged**
