### PR TITLE
Add table of contents to sea ice demo

### PR DESCRIPTION
**Pull request by acordonez**

### CODE REVIEW

**Review by durack1 — APPROVED** [review]
@acordonez looks good to me, thanks!

**Comment by lee1043** [comment]
Excellent, thank you for adding this, @acordonez!

One minor suggestion -- can you add the index number from the table of contents to the titles of sections as well?

**Review by lee1043 — APPROVED** [review]

**Comment by lee1043** [comment]
@acordonez checked links on [nbviewer](https://nbviewer.org/github/PCMDI/pcmdi_metrics/blob/7f78d0303cf98407038c82b77d9639df4759b845/doc/jupyter/Demo/Demo_9_seaIceExtent_ivanova.ipynb#top), and they work well!

**Comment by acordonez** [comment]
> Excellent, thank you for adding this, @acordonez!
> 
> One minor suggestion -- can you add the index number from the table of contents to the titles of sections as well?

Added

**Pull request merged**
