### PR TITLE
Open multiple files using xcdat

### PR DESCRIPTION
**Pull request by lee1043**
* Update xcdat version 
* Use xcdat `open_mfdataset` instead of `xcdat_open` that was defined locally in PMP
  * This update allows use of wildcard ('*' or '?') as a part of string giving path of input files. 
  * E.g., `modpath="/MY/FILES/*.nc"`

### CODE REVIEW

**Review by gleckler1 — APPROVED** [review]

**Comment by lee1043** [comment]
@tomvothecoder As discussed at the xcdat meeting, CI/CD build test is failing and with the [log](https://github.com/PCMDI/pcmdi_metrics/actions/runs/4811241828/jobs/8564986473?pr=926) that complains it cannot find xcdat 0.5.0. Could you please take a look?

```
Set up Conda Environment

Run conda-incubator/setup-miniconda@v2
Gathering Inputs...
Creating bootstrap condarc file in /home/runner/.condarc...
Ensuring installer...
Setup environment variables...
Parsing environment...
Configuring conda package cache...
Applying initial configuration...
Initializing conda shell integration...
Adding tools to 'base' env...
Ensuring environment...
Updating 'pcmdi_metrics_dev' env from conda env update...
  /usr/share/miniconda/condabin/conda env update --name pcmdi_metrics_dev --file conda-env/dev.yml
  Collecting package metadata (repodata.json): ...working... done
  Solving environment: ...working... failed
  Warning: 
  ResolvePackageNotFound: 
    - xcdat=0.5.0
  
  
  
  ResolvePackageNotFound: 
    - xcdat=0.5.0
  

Error: The process '/usr/share/miniconda/condabin/conda' failed with exit code 1
```

**Comment by tomvothecoder** [comment]
> @tomvothecoder As discussed at the xcdat meeting, CI/CD build test is failing and with the [log](https://github.com/PCMDI/pcmdi_metrics/actions/runs/4811241828/jobs/8564986473?pr=926) that complains it cannot find xcdat 0.5.0. Could you please take a look?
> 
> ```
> Set up Conda Environment
> 
> Run conda-incubator/setup-miniconda@v2
> Gathering Inputs...
> Creating bootstrap condarc file in /home/runner/.condarc...
> Ensuring installer...
> Setup environment variables...
> Parsing environment...
> Configuring conda package cache...
> Applying initial configuration...
> Initializing conda shell integration...
> Adding tools to 'base' env...
> Ensuring environment...
> Updating 'pcmdi_metrics_dev' env from conda env update...
>   /usr/share/miniconda/condabin/conda env update --name pcmdi_metrics_dev --file conda-env/dev.yml
>   Collecting package metadata (repodata.json): ...working... done
>   Solving environment: ...working... failed
>   Warning: 
>   ResolvePackageNotFound: 
>     - xcdat=0.5.0
>   
>   
>   
>   ResolvePackageNotFound: 
>     - xcdat=0.5.0
>   
> 
> Error: The process '/usr/share/miniconda/condabin/conda' failed with exit code 1
> ```

Hi @lee1043 I'm looking at this issue right now. Ignore my many commits for trying to fix this issue.

I think the root cause might be related to the GH Actions conda environment using a cached version of the packages.

**Comment by acordonez** [comment]
@lee1043  This fails for me using the demo dataset, where there is a single input file per model. Here's the error text, I can send the full  log if that's useful:
```
--- prepare mean climate metrics calculation ---
--- start mean climate metrics calculation ---
varname: rlut
level: None
reference_data_set (all):  ['alternate1', 'default']
ref: alternate1
ref_data_full_path: demo_data/pmpobs_v1.0/rlut/CERES-EBAF-4-0/v20210804/rlut_mon_CERES-EBAF-4-0_PCMDI_gn.200301-201812.AC.v20210804.nc
Traceback (most recent call last):
  File "/home/ordonez4/miniconda3/envs/pcmdi_metrics_dev/bin/mean_climate_driver.py", line 183, in <module>
    ds_ref = load_and_regrid(data_path=ref_data_full_path, varname=varname, level=level, t_grid=t_grid, decode_times=False, regrid_tool=regrid_tool, debug=debug)
  File "/home/ordonez4/miniconda3/envs/pcmdi_metrics_dev/lib/python3.9/site-packages/pcmdi_metrics/mean_climate/lib/load_and_regrid.py", line 25, in load_and_regrid
    ds = xc.open_mfdataset(data_path, data_var=varname_in_file, decode_times=decode_times)  # NOTE: decode_times=False will be removed once obs4MIP written using xcdat
  File "/home/ordonez4/miniconda3/envs/pcmdi_metrics_dev/lib/python3.9/site-packages/xcdat/dataset.py", line 205, in open_mfdataset
    ds = xr.open_mfdataset(
  File "/home/ordonez4/miniconda3/envs/pcmdi_metrics_dev/lib/python3.9/site-packages/xarray/backends/api.py", line 947, in open_mfdataset
    raise OSError("no files to open")
OSError: no files to open
```

**Comment by lee1043** [comment]
> @lee1043 This fails for me using the demo dataset, where there is a single input file per model. Here's the error text, I can send the full log if that's useful:
> 
> ```
> --- prepare mean climate metrics calculation ---
> --- start mean climate metrics calculation ---
> varname: rlut
> level: None
> reference_data_set (all):  ['alternate1', 'default']
> ref: alternate1
> ref_data_full_path: demo_data/pmpobs_v1.0/rlut/CERES-EBAF-4-0/v20210804/rlut_mon_CERES-EBAF-4-0_PCMDI_gn.200301-201812.AC.v20210804.nc
> Traceback (most recent call last):
>   File "/home/ordonez4/miniconda3/envs/pcmdi_metrics_dev/bin/mean_climate_driver.py", line 183, in <module>
>     ds_ref = load_and_regrid(data_path=ref_data_full_path, varname=varname, level=level, t_grid=t_grid, decode_times=False, regrid_tool=regrid_tool, debug=debug)
>   File "/home/ordonez4/miniconda3/envs/pcmdi_metrics_dev/lib/python3.9/site-packages/pcmdi_metrics/mean_climate/lib/load_and_regrid.py", line 25, in load_and_regrid
>     ds = xc.open_mfdataset(data_path, data_var=varname_in_file, decode_times=decode_times)  # NOTE: decode_times=False will be removed once obs4MIP written using xcdat
>   File "/home/ordonez4/miniconda3/envs/pcmdi_metrics_dev/lib/python3.9/site-packages/xcdat/dataset.py", line 205, in open_mfdataset
>     ds = xr.open_mfdataset(
>   File "/home/ordonez4/miniconda3/envs/pcmdi_metrics_dev/lib/python3.9/site-packages/xarray/backends/api.py", line 947, in open_mfdataset
>     raise OSError("no files to open")
> OSError: no files to open
> ```

@acordonez thank you for checking the demo. Can you please confirm you have the input file, `demo_data/pmpobs_v1.0/rlut/CERES-EBAF-4-0/v20210804/rlut_mon_CERES-EBAF-4-0_PCMDI_gn.200301-201812.AC.v20210804.nc`, otherwise you will need to run demo 0 to secure the data. May I have the full log as well?

**Comment by lee1043** [comment]
@tomvothecoder Thank you very much for making the build test working! That is a huge help!

**Comment by acordonez** [comment]
@lee1043  you're right, once I updated the obs demo data this is working now. I don't have any xml clims to test, but I can also run that if there is some data you can point me to.

**Comment by lee1043** [comment]
@acordonez thank you for checking. I think it is okay to merge. Merging this now.

**Pull request merged**
