### PR TITLE
Add enso_metrics

### PR DESCRIPTION
**Pull request by acordonez**
Add enso_metrics dependency to dev environment yaml.

### CODE REVIEW

**Comment by gleckler1** [comment]
@acordonez Do we still rely on the CI/CD checks?

**Comment by acordonez** [comment]
@gleckler1  Yes, but these are checking things like formatting mostly. The metrics testing isn't built out yet.

**Review by lee1043 — APPROVED** [review]

**Comment by lee1043** [comment]
Thank you for the update. Can we specify version just in case?

**Comment by lee1043** [comment]
@gleckler1 yes, but not through circle ci. The CI/CD process was switched to use Github Action, and at the moment, mostly about code styling.

**Comment by acordonez** [comment]
@lee1043 Added and tested the version.

**Pull request merged**
