### PR TITLE
Issue403 durack1 augment pmp traceablity from source

### PR DESCRIPTION
**Pull request by doutriaux1**
@durack1 I put in quite a few `tweaks` please review the changes

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 looks like a test failure..

**Comment by doutriaux1** [comment]
@durack1 flake8 on my crunchy was older. Cleaned this up. Please review

**Comment by doutriaux1** [comment]
@durack1 new provenance:
```
    "provenance": {
        "platform": {
            "OS": "Linux",
            "Version": "2.6.32-573.22.1.el6.x86_64",
            "Name": "crunchy.llnl.gov"
        },
        "userId": "doutriaux1",
        "osAccess": false,
        "commandLine": "/export/doutriaux1/anaconda2/envs/2.8.1-nox/bin/pcmdi_metrics_driver.py -p test/pcmdi/gensftlf_test.py",
        "date": "2017-01-06 15:36:33",
        "conda": {
            "Platform": "linux-64",
            "Version": "4.2.13",
            "IsPrivate": "False",
            "envVersion": "4.2.13",
            "buildVersion": "2.0.10",
            "PythonVersion": "2.7.11.final.0",
            "RootEnvironment": "/export/doutriaux1/anaconda2  (writable)",
            "DefaultEnvironment": "/export/doutriaux1/anaconda2/envs/2.8.1-nox"
        },
        "packages": {
            "cdms": "2.8.1",
            "CDP": "1.0.1",
            "cdtime": "2.8",
            "cdutil": "2.8",
            "esmf": "ESMF_6_3_0rp1_ESMP_01",
            "genutil": "2.8",
            "python": "2.7.12",
            "matplotlib": "1.5.3",
            "numpy": "1.11.2",
            "vtk": "7.1.0.2.8",
            "vcs": "2.8",
            "PMP": "g1629bdd",
            "PMPObs": null
        },
        "openGL": {
            "vendor": "VMware, Inc.",
            "renderer": "Gallium 0.4 on llvmpipe (LLVM 3.6, 128 bits)",
            "version": "2.1 Mesa 11.0.7",
            "shading language version": "1.30",
            "GLX": {
                "client": {
                    "vendor": "Mesa Project and SGI",
                    "version": "1.4"
                },
                "version": "1.4",
                "server": {
                    "vendor": "SGI",
                    "version": "1.4"
                }
            }
        }
    }
}
```

**Comment by durack1** [comment]
@doutriaux1 looks good.. We should also use this provenance stuff for diagnostics when we have install problems..

**Comment by doutriaux1** [comment]
@durack1 yes I was actually thinking of adding a `verbose` or `debug` option to the provenance function to dump even mor info (like ALL the packages installed, etc...)

**Pull request merged**
