### PR TITLE
pre-commit check compliant for github action

### PR DESCRIPTION
**Pull request by lee1043**
In adaption of pre-commit-hook in the workflow of pmp, codes need to be compliant to the given rules, as discussed in https://github.com/PCMDI/pcmdi_metrics/pull/788 and https://github.com/PCMDI/pcmdi_metrics/pull/788#discussion_r742082484

### CODE REVIEW

**Comment by lee1043** [comment]
This PR is a mass diff as @tomvothecoder predicted in his [comment](https://github.com/PCMDI/pcmdi_metrics/pull/788#discussion_r742082484), but mostly for reformatting codes to follow style rules (flake8, black, isort, etc). Many thanks to @tomvothecoder for his comments which helped me learn a lot about setting up the github action workflow. There was a steep learning curve but I think I am getting better with it.

@tomvothecoder, could you please take a look the revised [.pre-commit-config.yaml](https://github.com/PCMDI/pcmdi_metrics/blob/8e87b88a945738161de92647d36295f81c19c3b4/.pre-commit-config.yaml) and [setup.cfg](https://github.com/PCMDI/pcmdi_metrics/blob/8e87b88a945738161de92647d36295f81c19c3b4/setup.cfg) files to see if they make sense to you? 

@acordonez, could you please help running demos using this branch to see if there is any impact? I expect the result should not be affected by this change. I will also run the demos on my end, but wanted to have additional test from different end to be safer. Please also note that some files under `cmec` directory has been changed as well, but just about formatting and style.

@gleckler1, I have reduced flake8 error messages from hundreds to tens, and following two files still have issues and I don't have good ideas how best to fix. Any advice? If that to be too much hassle, I think I can leave them out for now (exclude the 2 files from flake8 test, until they got fixed).

[`pcmdi_metrics/pcmdi/scripts/pcmdi_compute_climatologies-CMOR.py`](https://github.com/PCMDI/pcmdi_metrics/blob/8e87b88a945738161de92647d36295f81c19c3b4/pcmdi_metrics/pcmdi/scripts/pcmdi_compute_climatologies-CMOR.py):
```
320:43: F821 undefined name 'r'
320:46: F821 undefined name 'i'
320:49: F821 undefined name 'p'
```

[`pcmdi_metrics/devel/monsoon_wang/scripts/bar_chart_monsoon_precip_index.py`](https://github.com/PCMDI/pcmdi_metrics/blob/8e87b88a945738161de92647d36295f81c19c3b4/pcmdi_metrics/devel/monsoon_wang/scripts/bar_chart_monsoon_precip_index.py):
```
218:18: F821 undefined name 'mod_name'
220:32: F821 undefined name 'mod_name'
223:30: F821 undefined name 'mod_name'
226:10: F821 undefined name 'numexpts'
228:23: F821 undefined name 'numexpts'
230:27: F821 undefined name 'numexpts'
231:31: F821 undefined name 'numexpts'
244:27: F821 undefined name 'numexpts'
```

**Comment by tomvothecoder** [comment]
Awesome job picking up the QA tools quickly Jiwoo! It's definitely not an easy task.

> @tomvothecoder, could you please take a look the revised .pre-commit-config.yaml and setup.cfg files to see if they make sense to you?

Those files look good to me.

> @acordonez, could you please help running demos using this branch to see if there is any impact? I expect the result should not be affected by this change. I will also run the demos on my end, but wanted to have additional test from different end to be safer. Please also note that some files under cmec directory has been changed as well, but just about formatting and style.

Yes, the results should be identical since it is simply code and import formatting. It would still be good to validate though.

Note, one potential issue with using `isort` is if you define env variables (e.g., turning off MPI with cdms2) or set configurations for libraries like matplotlib (e.g., `matplotlib.use("Agg") above certain imports. In those cases, you'd have to ignore sorting the lines for those specific imports. **I performed a quick search for these cases, but luckily they don't apply.**

> @gleckler1, I have reduced flake8 error messages from hundreds to tens, and following two files still have issues and I don't have good ideas how best to fix. Any advice? If that to be too much hassle, I think I can leave them out for now (exclude the 2 files from flake8 test, until they got fixed).

That flake8 error `F821 undefined name` is saying that those variables aren't defined in the current scope, but are being referenced. The fix is to either remove the lines that reference those undefined variables, or add `noqa: F821` (not suggested since it leaves broken code in place).

---
On a side note, I noticed the GH Actions build job fails on the "Run Tests" step because there are no tests available to run.
```
============================ no tests ran in 3.17s =============================
Error: Process completed with exit code 5.
```
https://github.com/PCMDI/pcmdi_metrics/runs/4100746374?check_suite_focus=true#step:5:120

I'm currently exploring a few possible workarounds for this.

**Comment by tomvothecoder** [comment]
Hey @lee1043, I have addressed the GH Actions build issues in PR #794. Please review the summary of changes (it includes removing `mypy` for now).

That PR will merge into this PR.

**Comment by acordonez** [comment]
>     * @acordonez, could you please help running demos using this branch to see if there is any impact? I expect the result should not be affected by this change. I will also run the demos on my end, but wanted to have additional test from different end to be safer. Please also note that some files under `cmec` directory has been changed as well, but just about formatting and style.

I ran all the notebooks. The two issues I ran into are 
1) the MJO, Monsoon Sperber, and Variability Modes drivers can't import VCS 
2) I don't have the old style ENSO data anymore, so while I can run the ENSO notebook without error it doesn't generate metrics.
Let me know if these results are expected or if I should do more testing.

I also did a cmec-driver run using the mean climate driver, which was successful.

**Comment by gleckler1** [comment]
@acordonez Let's see what JL says about the vcs conflict.  We know we need to move away from this but I'm not sure if he is ready for doing that with MJO, monsoon sperber, and variability.   

Are we missing some data for the ENSO demo?  I thought we were successful in switching to the new style.

**Comment by lee1043** [comment]
@acordonez Thanks for checking this. While I am refactoring vcs plots (https://github.com/PCMDI/pcmdi_metrics/pull/786), I think it is okay to check output json files to see if there is any noticeable difference. Sorry, I should have clarified this in advance. 

By the way could you tell me little bit more what do you mean by no old style ENSO data?

**Comment by lee1043** [comment]
> Hey @lee1043, I have addressed the GH Actions build issues in PR #794. Please review the summary of changes (it includes removing `mypy` for now).
> 
> That PR will merge into this PR.

@tomvothecoder thanks for the PR. I agree that removing `mypy` makes sense to me because most of PMP code has been wrote with dynamic typing, instead of static typing as checked by [`mypy`](https://mypy.readthedocs.io/en/stable/index.html).

**Comment by lee1043** [comment]
> I also did a cmec-driver run using the mean climate driver, which was successful.

@acordonez glad to hear that! Thank you for checking.

**Comment by acordonez** [comment]
> @acordonez Thanks for checking this. While I am refactoring vcs plots (#786), I think it is okay to check output json files to see if there is any noticeable difference. Sorry, I should have clarified this in advance.
> 
> By the way could you tell me little bit more what do you mean by no old style ENSO data?

The VCS issue is blocking the metrics output for MOV - the driver seems to fail before writing the JSON output. I'd have to spend some time editing the driver code to make this pass. 

I'm having some kind of issue with the ENSO driver producing metrics. I thought maybe I was using the wrong data version or obs dictionary but if we merged that change, it must be something else.

**Comment by lee1043** [comment]
@acordonez I think turning off plot option in parameter files should prevent calling vcs module, but please let me know if not. 

@gleckler1 do you have any idea why the file is not available, or who to talk to?

**Comment by gleckler1** [comment]
@lee1043 @acordonez I've just looked on pcmdiweb and the only relevant file I see is pmp_enso_tutorial_files.txt 
Can you try that?  The date on it is May 04 2021.   It's better to have the version in the filename, but I'm not sure where the pmp_enso_tutorial_files.v20210823.txt came from.   Late Aug was pretty busy for me, this could be a loose end for us to resolve.

**Comment by gleckler1** [comment]
@lee1043 @acordonez  Also, I see this file (pmp_enso_tutorial_files.txt) is for a demo, which I don't recall necessary being the same data as for running all the enso metrics.

**Comment by acordonez** [comment]
@gleckler1 @lee1043 https://pcmdiweb.llnl.gov/pss/pmpdata/pmp_enso_tutorial_files.txt does work. I don't remember why a different version is in the ENSO notebook. I can make a quick PR to fix that

**Comment by lee1043** [comment]
@gleckler1 @acordonez in the [ENSO notebook](https://github.com/PCMDI/pcmdi_metrics/blob/master/doc/jupyter/Demo/Demo_6_ENSO.ipynb) cell [1] I see there are following two lines: 

```python
#r = requests.get("https://pcmdiweb.llnl.gov/pss/pmpdata/pmp_enso_tutorial_files.txt")
r = requests.get("https://pcmdiweb.llnl.gov/pss/pmpdata/pmp_enso_tutorial_files.v20210823.txt")
```
I found a related email thread about having this while and forwarded to both of you.

**Comment by acordonez** [comment]
@lee1043  using the no plot option wasn't sufficient; I'm getting an import error due to VCS just for calling the help statement. Since there's just one script each using VCS in MOV and MJO I locally set those functions to not import VCS and return. Then I could run the metrics, which look the same as before.

**Comment by tomvothecoder** [comment]
> 1. the MJO, Monsoon Sperber, and Variability Modes drivers can't import VCS

@acordonez Just wondering if you're using the latest [`conda-env/dev.yml`](https://github.com/PCMDI/pcmdi_metrics/blob/master/conda-env/dev.yml) to run these notebooks? This env doesn't include `vsc` and `vcsaddons`, so you'll run into `ModuleNotFoundError: No module named 'vcs'`.

**Comment by lee1043** [comment]
@acordonez I merged the PR #797 that is for removing VCS dependencies to this branch, so I think turning on plot option in parameters should have no problem by now. 

In separate, somehow I am failing running Demo0 and Demo1, which I think it might not resulted by changes in this PR but by changes in directory structure in demo data or failure of some files in the demo data directory. I will investigate this.

**Comment by lee1043** [comment]
> > 1. the MJO, Monsoon Sperber, and Variability Modes drivers can't import VCS
> 
> @acordonez Just wondering if you're using the latest [`conda-env/dev.yml`](https://github.com/PCMDI/pcmdi_metrics/blob/master/conda-env/dev.yml) to run these notebooks? This env doesn't include `vsc` and `vcsaddons`, so you'll run into `ModuleNotFoundError: No module named 'vcs'`.

This should be no longer issue as I removed VCS. Thanks for pointing it out.

**Comment by lee1043** [comment]
I have double-checked all demos results are consistent to that in the current master. With that, I am merging this PR.

**Pull request merged**
