### PR TITLE
fix #300

### LINKED ISSUE #300: test suite should not depend on obs json file

### PR DESCRIPTION
**Pull request by doutriaux1**
use a custom obs json file ofr tests so that changing to good one won't affect tests
upped precision to 3 digits

### CODE REVIEW

**Comment by doutriaux1** [comment]
@durack1 @gleckler1

**Comment by durack1** [comment]
@doutriaux1 should we wait for @jservonnat to test this out.. Or just merge and then get some feedback?

**Comment by doutriaux1** [comment]
I don't think it will help with @jservonnat issue. I'm planning on doing this in a separte PR, but upping to 3 sig digits should help

**Comment by durack1** [comment]
@doutriaux1 did you want to create a dedicated issue for the 3 digits/precision fix, as it's currently associated with #279 which isn't a targeted issue at all?

Want me to merge now?

**Comment by durack1** [comment]
@doutriaux1 the `CMake` issue https://github.com/UV-CDAT/uvcdat/issues/1839 is still occurring on linux: https://travis-ci.org/PCMDI/pcmdi_metrics/jobs/110494849#L4208-L4219

@aashish24 any ideas what's happening here?

**Comment by doutriaux1** [comment]
@durack1 yes I know still one more issue for @gleckler1 before I get to this.

**Comment by durack1** [comment]
@doutriaux1 FYI https://github.com/PCMDI/pcmdi_metrics/issues/303 now is a dedicated issue for test result precision, it simplifies #279 which should be close-able once the `travis` CMake issue is solved.

**Comment by durack1** [comment]
@doutriaux1 is this good to go? We're hoping not to be holding you up with this stuff..

**Comment by doutriaux1** [comment]
@durack1 I think so. Please test first.

**Comment by durack1** [comment]
@doutriaux1 I'm unable to complete a fresh build to test - can you review and merge https://github.com/UV-CDAT/uvcdat/pull/1840 please?

**Pull request merged**
