### PR TITLE
newer masking from Denis

### PR DESCRIPTION
**Pull request by doutriaux1**
ok @gleckler1 @durack1 @dnadeau4 same deal but with faster code from Denis 
(6mn vs 52mn) again only cdms is different. I need you guys input. Do NOT merge.

### CODE REVIEW

**Comment by dnadeau4** [comment]
Ok did not see that you have 2 issues.

**Comment by doutriaux1** [comment]
@gleckler1 thanks for the suggestion pltting the climo solved the issue.

bellow the old 2.8 climos:
v28

and the new climo with the new regridder:
nightly

@dnadeau4 this is very important i will try to give a short script to work on for this.

**Comment by gleckler1** [comment]
Wow… not even for a masked case!?

**Comment by doutriaux1** [comment]
@dnadeau4 data can be accessed form root of this repo
```python
import cdms2
f=cdms2.open("test/pcmdi/data/tas_GFDL-ESM2G_Amon_piControl_000101-010012-clim01.xml")
t_grid = cdms2.createUniformGrid(-88.875, 72, 2.5, 0, 144, 2.5)                                  
s=f("tas_ac")
s2=s.regrid(t_grid)                                                                                                                                                                                                                                                           
import vcs                                                                                                                               
x=vcs.init()                                                                                                                             
x.plot(s2)                                                                                                                               
x.png("regrid")                                                                                                                          
```

**Pull request closed without merging**
