### PR TITLE
Issue413 durack1 pcmdi logo for branding

### LINKED ISSUE #413: Provide PCMDI logo for png branding
Add new png for PCMDI branding of png output - keep under 500KB.

Should be under share/pcmdi/

### PR DESCRIPTION
**Pull request by durack1**
Fix #413 - Added png logos for branding

@gleckler1 @doutriaux1 as discussed in #413 - oblong is the non-gridded version

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 it seems the [portrait issue is still alive in this PR](https://travis-ci.org/PCMDI/pcmdi_metrics/builds/160286798) can you take a look please?

**Comment by doutriaux1** [comment]
@durack1 push and pr behave differently, I think one merges master in first the other  not. Try to merge master into that branch

**Comment by durack1** [comment]
@doutriaux1 ok trying again.. This might be a case of needing to merge #417 into master before updating this branch again..

**Comment by durack1** [comment]
@doutriaux1 ok good to go

**Comment by doutriaux1** [comment]
@durack1 I'll edit this branch to actually use the log, before merging. Ok?

**Comment by durack1** [comment]
@doutriaux1 perfect, it would be better to actually be using these rather than just dumping them.. So please go ahead..

**Comment by durack1** [comment]
@doutriaux1 the quality of the images are pretty terrible - both the logo and the text for the colorbar, and the top of the colorbar too, see below:
badres

**Pull request merged**
