### PR TITLE
Update portrait and parallel plot examples for mean climate

### PR DESCRIPTION
**Pull request by lee1043**
Update portrait and parallel plot examples for mean climate to use archived raw json from https://github.com/PCMDI/pcmdi_metrics_results_archive, instead of tar.gz

### CODE REVIEW

**Comment by acordonez** [comment]
@lee1043 This got lost in my inbox! I saw it's merged so I'll pull main and give it a final test.

**Comment by lee1043** [comment]
@acordonez it was a small minor change only on notebook so I was thinking it may be good to go, but additional test is always appreciated! Thank you :)

**Comment by acordonez** [comment]
@lee1043 I get 404 Not Found errors for the JSON downloads in parallel_coordinate_plot_mean_clim.ipynb and portrait_plot_mean_clim.ipynb. 
I was able to run the notebooks by changing the url text "https://raw.githubusercontent.com/PCMDI/pcmdi_metrics_results_archive/archive_raw_json/" to "https://raw.githubusercontent.com/PCMDI/pcmdi_metrics_results_archive/main/" in the download cell. Does that point to the right files?

**Comment by lee1043** [comment]
@acordonez thank you for checking! Yes, `main` is correct. I might missed to update notebook after I merge branch in the PMP result repo.

**Comment by lee1043** [comment]
@acordonez could you please upload your patched notebook via a new PR?

**Pull request merged**
