### PR TITLE
Create template parameter file for E3SM

### PR DESCRIPTION
**Pull request by acordonez**
A new sample parameter file is added to sample_setups/pcmdi_parameter_files/mean_climate to help the E3SM team use the PMP.

I have tested this by running `mean_climate_driver.py -p e3sm_parameterfile.py` (after adding a default "rt" value in pcmdiobs2_clims_byVar_catalogue_v20200615.json).

### CODE REVIEW

**Comment by acordonez** [comment]
@lee1043 @gleckler1 Here's the working parameter file I have started for E3SM. I can add a small readme file if Peter doesn't mind potentially resolving conflicts with his README in branch 652_pjg_add_mean_interal_params.

**Comment by gleckler1** [comment]
@acordonez Looks good!  Go idea to add a README.   I can deal with the conflict when we push 652.  Once you've got README done I'll merge

**Comment by acordonez** [comment]
@gleckler1 Added the README

**Comment by gleckler1** [comment]
@acordonez  OK, I'll wait until tests are done.

**Pull request merged**
