### PR TITLE
Issue 316 regions

### PR DESCRIPTION
**Pull request by doutriaux1**
@durack1 @glecker1 let's review carefully

### CODE REVIEW

**Comment by doutriaux1** [comment]
@gleckler1 I forgot to update the all_options param file Let's talk tomorrow

**Comment by durack1** [comment]
@doutriaux1 looks like the [graphics tests are continuing to fail](https://travis-ci.org/PCMDI/pcmdi_metrics/builds/144610219#L1231-L1249) everything else looks like it's working well..

**Comment by gleckler1** [comment]
@durack1 @doutriaux1  graphics failures much less of a concern that the statistics results

**Comment by durack1** [comment]
@gleckler1 if we're trying to run a tight ship here, I suggest we don't allow problems to accumulate.. So if there is an error fix it.

**Comment by doutriaux1** [comment]
taking a stab at it today.

**Comment by gleckler1** [comment]
@doutriaux1 checking now... initial tests look good as does organization of output interpolated clims.... one issue is that for single level data (e.g., 'ta-850') issue #367 has not been fixed, e.g.:  
cmip5.CCSM4.historical.r1i1p1.mo.Amon.ta_85000-850.ver1.1980-2005.interpolated.linear.2.5x2.5.NHEX.AC.nc

**Comment by gleckler1** [comment]
@doutriaux1 awesome advancement of the PMP!  Apart from issue #367 the only problem I've found is with variable 'tas' (see below) ... maybe has to do with singleton dimension?

 REGION: {'domain': Selector(<cdutil.region.DomainComponent instance at 0x7f4160fc5f80>), 'id': 'SHEX'}
 OBS SHAPE IS  (12, 25, 144)
 tas   ACCESS1-0   (12, 25, 144)   (12, 25, 144)    default
 REGION: {'domain': Selector(<cdutil.region.DomainComponent instance at 0x7f4160f88368>), 'id': 'NHEX'}
 OBS SHAPE IS  (12, 24, 144)
 tas   ACCESS1-0   (12, 24, 144)   (12, 24, 144)    default
 REGION: {'id': 'global'}
 OBS SHAPE IS  (12, 72, 144)
 tas   ACCESS1-0   (12, 72, 144)   (12, 72, 144)    default
 REGION: {'id': 'land', 'value': 100.0}
 failed with 4D OBS tas default OBS instance has no attribute 'region'
 REGION: {'id': 'ocean', 'value': 0.0}
 failed with 4D OBS tas default OBS instance has no attribute 'region'

**Comment by doutriaux1** [comment]
@durack1 @gleckler1 test suite is fixed now! param file updated. Ready to be merged at your convenience.

**Comment by gleckler1** [comment]
@doutriaux1 Everything is looking good but still getting error below with TAS... with attached parameter file...

OBS SHAPE IS  (12, 24, 144)
 tas   ACCESS1-0   (12, 24, 144)   (12, 24, 144)    default
 REGION: {'id': 'global'}
 OBS SHAPE IS  (12, 72, 144)
 tas   ACCESS1-0   (12, 72, 144)   (12, 72, 144)    default
 REGION: {'id': 'land', 'value': 100.0}
 failed with 4D OBS tas default OBS instance has no attribute 'region'
 REGION: {'id': 'ocean', 'value': 0.0}
 failed with 4D OBS tas default OBS instance has no attribute 'region'

**Comment by gleckler1** [comment]
@doutriaux1

**Comment by gleckler1** [comment]
@doutriaux1 appended .txt to parameter file since upload does not accept .py
[test_regional.py.txt](https://github.com/PCMDI/pcmdi_metrics/files/366597/test_regional.py.txt)

**Comment by durack1** [comment]
@gleckler1 did you mean to close this PR without merging the branch into `master`? Because reading the above that's exactly what has been done.

**Comment by gleckler1** [comment]
@doutriaux1 @durack1  Did not mean do close it.  Waiting for tas bug to be fixed before accepting pull request...

**Comment by durack1** [comment]
@doutriaux1 was also planning on getting the `OS X` graphics working too.. So then we have an active `linux` AND `OS X` test running.. This would be great!

**Comment by doutriaux1** [comment]
@durack1 the mac will probably happen in another branch later, this is not a high priority issue.

**Comment by doutriaux1** [comment]
@gleckler1 should have fixed your issue and also Curt issue while at it.

**Comment by gleckler1** [comment]
@doutriaux1 is creation of filename for single level data of interpolated clims also fixed?

**Comment by doutriaux1** [comment]
in another PR after this one.

**Comment by durack1** [comment]
@gleckler1 @doutriaux1 woo hoo.. `Travis` is all green (for linux at least!)

**Comment by durack1** [comment]
@doutriaux1 @gleckler1 what does this merge close, we have standing: #252, #343, #361, #367, #372, #373, #374 and #375 - or see https://github.com/PCMDI/pcmdi_metrics/milestone/7

**Comment by gleckler1** [comment]
@doutriaux1 @durack1  it looks like it does not include the "demo" PR #376 :
https://github.com/PCMDI/pcmdi_metrics/pull/376/files

**Pull request merged**
