### PR TITLE
CMIP5 and 6 comparing portrait and parallel coordinate plot

### PR DESCRIPTION
**Pull request by lee1043**
Jupyter notebooks for creation of portrait and parallel coordinate plots for comparing CMIP5 and CMIP6 models.

### CODE REVIEW

**Comment by lee1043** [comment]
NOTE: Need to update to use `Metrics` class to simplify process in the notebook.

**Comment by lee1043** [comment]
@acordonez I think this PR is ready for review, could you verify notebooks are working well on your end too when you have time?

**Comment by acordonez** [comment]
@lee1043 The notebooks worked for me. One thing I noticed is that I had some old files in my portrait_plot/json_files that hadn't downloaded correctly in a past test (contained 404 errors). This caused a failure in the portrait plot notebook until I removed the existing json_files folder and started from scratch. Would the notebook still give the correct results if users had old versions of the same data in json_files? Should the json_files be cleaned before running each time?

**Review by acordonez — COMMENTED** [review]
Deleted my prior comment and reposting as a review - The notebooks worked for me. One thing I noticed is that I had some old files in my portrait_plot/json_files that hadn't downloaded correctly in a past test (contained 404 errors). This caused a failure in the portrait plot notebook until I removed the existing json_files folder and started from scratch. Would the notebook still give the correct results if users had old versions of the same data in json_files? Should the json_files be cleaned before running each time?

**Comment by lee1043** [comment]
@acordonez thank you for checking. I have assumed that user will run from scratch -- starting from downloading, but I see your point -- thanks for pointing it out. I might have to implement more elegant way of downloading, but I think that is for the next PR unless we find any quick solution.

**Review by acordonez — APPROVED** [review]

**Pull request merged**
