### PR TITLE
Land sea mask generation

### PR DESCRIPTION
**Pull request by lee1043**
- [x] Add the land sea mask generation capability using `regionmask`
- [x] Replace CDAT's landseamask generation to the new function
  - [x] mean climate
  - [x] precipitation variability

### CODE REVIEW

**Comment by lee1043** [comment]
Sanity check:
- [ ] demo 1b notebook results are consistent
- [ ] demo 7 notebook results are consistent

**Comment by acordonez** [comment]
I'll test this out in the extremes metrics branch

**Comment by acordonez** [comment]
@lee1043 This looks fine to me:

Untitled

**Review by acordonez — APPROVED** [review]

**Comment by acordonez** [comment]
> @lee1043 This looks fine to me:
> 
> Untitled

I actually did not implement the new mask correctly and I believe this is using the pcmdi_utils version...still working on testing the extremes

**Comment by lee1043** [comment]
@acordonez Thank you for checking. Please let me know when you done testing this with extreme branch. If merging this PR into main would better help your testing of extreme branch, I can also do that.

**Comment by acordonez** [comment]
This time I should be using the new land/sea mask, I pulled all the other code out of my branch:

Screenshot 2023-12-18 at 3 31 10 PM

**Pull request merged**
