### PR TITLE
Sea ice metrics beta

### PR DESCRIPTION
**Pull request by acordonez**
Adding the beta sea ice driver and tutorial

### CODE REVIEW

**Comment by lee1043** [comment]
Can you add `__init__.py` file in the https://github.com/PCMDI/pcmdi_metrics/tree/405_sic_ao/pcmdi_metrics/sea_ice/lib?

**Comment by acordonez** [comment]
@lee1043  Added!

**Comment by durack1** [comment]
Just adding myself to watch - was hoping to update email template and send later tonight (as we received the email from Younjoo)

**Comment by lee1043** [comment]
@acordonez thank you for the excellent work in tight timeline! This is really great. I was able to run the notebook without any issues. I just added a minor update to add wall clock time, as @durack1 suggested. `nc-time-axis` that was needed for the plotting part was added to `dev.yml`. I am merging this to the main branch.

Once merged, @durack1 and @acordonez, would you try run this through the binder hub? I will do so as well.

**Review by lee1043 — APPROVED** [review]

**Pull request merged**
