### PR TITLE
pings pcmdi db to record a call to pcmdi_metrics

### LINKED ISSUE #282: User registration - how to capture info
This needs to be considered..

### PR DESCRIPTION
**Pull request by doutriaux1**
fix #282

### CODE REVIEW

**Comment by doutriaux1** [comment]
@durack1 @gleckler1

**Comment by durack1** [comment]
@doutriaux1 let's wait till we can check this and make it work - and @chaosphere2112 has the server back up and running..

**Comment by chaosphere2112** [comment]
@durack1 @doutriaux1 Alright, the analytics server has been upgraded to Django 1.8 and refactored to store data in a more compressed form than previously. Currently there's no web-based way to get access to the data, but it's all stored in the DB and I can get at it from the command line on the server.

**Comment by durack1** [comment]
@chaosphere2112 @doutriaux1 ok, so we're probably at the stage of turning it on and testing things out.. And seeing if @chaosphere2112 can make sense of what we're logging..

**Comment by durack1** [comment]
@doutriaux1 I'm reluctant to merge until the travis builds are passing fine.. Do you know what is going on here?

**Pull request merged**
