### PR TITLE
446 pjg add rmsc

### PR DESCRIPTION
**Pull request by gleckler1**
added IN #439 to this.   Tried to update test results, not sure that is working...

### CODE REVIEW

**Comment by gleckler1** [comment]
@durack1 @doutriaux1 
I tried updating test results before pull request.   I have no idea why this is failing...
surely its not 
ImportError: libjpeg.so.9: cannot open shared object file: No such file or directory
Which has nothing to do with what I've added on this branch.

Can a tester expert pls sort this out?

**Comment by durack1** [comment]
@gleckler1 the test is using the nightly UVCDAT, which itself seems to be broken: https://travis-ci.org/UV-CDAT/uvcdat

While I have you, can you please answer the query at #403?

**Comment by zshaheen** [comment]
@gleckler1 @durack1 I'm in the process of porting the tests to the new version of pmp, so you guys don't have to worry about this for now. I should be done around next week.

**Comment by gleckler1** [comment]
@zshaheen @doutriaux1 @durack1 @lee1043   Sounds interesting!  What is the new version of the PMP?  Shouldn't it be going through the usual process of pull request reviewing?..  its not clear why it (in progress) should be effecting (breaking the test suite) if it has not been merged into master.   Lets have a meeting next week to discuss this.  Clim scientists need to be aware of any changes that are being made that might impact how we are developing things on a day to day basis.

**Comment by zshaheen** [comment]
@gleckler1 @durack1 @doutriaux1 @lee1043 Yeah, a meeting would be fine. The new version fits into the design of CDP. In addition, I'm just refactoring `pcmdi_metrics_driver.py` to work with obs vs obs and model vs model. And after this, we'll be adding in the viewer that Dean talked to you and Karl about.

I have my own fork which has the changes, and when ready, I'll issue a pull request. The only reasons it would break the test suite is due to refactoring `pcmdi_metrics_driver.py` and the change in vocabulary we discussed with Jerome.

**Comment by gleckler1** [comment]
@durack1 @zshaheen @doutriaux1 @lee1043 So, PG presumes we can merge this master even though the tests are broken.   Any arguments against that?

**Comment by zshaheen** [comment]
@gleckler1 Sure, I think I can get my versions of the tests working with the new stuff you did. Guess it doesn't really matter, since come this January we'll lose all of our funding.

**Comment by gleckler1** [comment]
@durack1 @zshaheen @doutriaux1 Its been almost a week... it is a problem that the failed tests are holding things up.

**Comment by durack1** [comment]
@gleckler1 can you merge in the branch at PCMDI/pcmdi_metrics#448 (`travis_fix`), hopefully if this solves the travis test failure then we're good to merge

**Comment by durack1** [comment]
@gleckler1 the fix noted above is now in master so a rebase (with master) should get you green tests and voila - merge-a-roony

**Comment by durack1** [comment]
@doutriaux1 ok it's getting further, [now](https://travis-ci.org/PCMDI/pcmdi_metrics/builds/176860166#L1270-L1275):
```
FAIL: flake8 (test_flake8.TestFlake8)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/PCMDI/pcmdi_metrics/test/test_flake8.py", line 36, in flake8

    self.assertTrue(out == "")

AssertionError: False is not true
```

**Comment by durack1** [comment]
@doutriaux1 are PRs auto-flaked? That would be good if they could be..

**Pull request merged**
