### PR TITLE
272 pjg add std newsoln

### PR DESCRIPTION
**Pull request by gleckler1**
@doutriaux1 @durack1 Need to add STD calcs so that we can produce Taylor Diagrams!  Pls check and include in master asap.

### CODE REVIEW

**Comment by durack1** [comment]
TDs? is that a kind of cocktail?

**Comment by gleckler1** [comment]
Taylor Diagrams but I guess you knew that.

**Comment by gleckler1** [comment]
@doutriaux1 can you give this a green light?

**Comment by doutriaux1** [comment]
@gleckler1 we will need to update the tests first to reflect these additional numbers

**Comment by gleckler1** [comment]
@doutriaux1  I'm confused - I thought the current status was the test were not working and not consistent across platforms.  If true that needs to be resolved irrespective of adding the SDs.   I have already updated the json files on master to include these because we need them for producing TDs and we are on home stretch of getting things in order for v1.1    Lets talk about this.

**Comment by doutriaux1** [comment]
it is working, just some numbers are different between Linux and Mac, we need to study that, but we do need to update the test result anyway with the newer (additional) numbers from this, otherwise ALL test on ALL platforms will fail forever.

**Comment by gleckler1** [comment]
@doutriaux1  okbyme ... I have no idea what that involves so PG presumes CD will update test results?

**Comment by doutriaux1** [comment]
@gleckler1 I will do it but with you next to me so you can learn
 1 to run the suite
 2 to update it

**Comment by gleckler1** [comment]
@doutriaux1 PG thinks ready to be pushed

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 I'm struggling to mv forward without having pull requests more efficiently reviewed and pushed.   please...

**Comment by durack1** [comment]
@gleckler1 can you make a trivial change and push again so the tests are re-triggered.. Then if they pass (and we confirm they run) then voila merge-aroony..

**Comment by doutriaux1** [comment]
I merged it into my branch and I'm rewriting the test, they will both be merged at once.

**Pull request merged**
