### PR TITLE
Visualization demo for user-model

### PR DESCRIPTION
**Pull request by lee1043**
- Add Metrics class written by @jkrasting 
- Develop a visualization demo for user model and its comparison to CMIP models, by downloading archived PMP results from https://github.com/PCMDI/pcmdi_metrics_results_archive

### CODE REVIEW

**Comment by acordonez** [comment]
@lee1043  Trying it out now

**Review by acordonez — APPROVED** [review]

**Comment by acordonez** [comment]
@lee1043 Notebook works for me.

**Comment by lee1043** [comment]
NOTE: Add Taylor Diagram?

**Comment by jkrasting** [comment]
Looks great @lee1043 - thanks!

**Pull request merged**
