### PR TITLE
589 ljw new metrics uw

### PR DESCRIPTION
**Pull request by lee1043**
MJO metrics to master. PR generated for tracking changes. NOT ready for merging until told.

### CODE REVIEW

**Comment by lee1043** [comment]
@muryanto1 I don't have a good idea for the cause of circleci failure, would you mind taking a look and sharing your insights?

**Comment by muryanto1** [comment]
@lee1043 merge my changes from libnetcdf_variant to your branch. It should help.
I cannot merge my changes from "libnetcdf_variant" branch since tests were failing. I do not have enough permission to merge since tests were failing.

**Comment by lee1043** [comment]
@muryanto1 thanks for the comment. I just merged the PR.

**Comment by lee1043** [comment]
@muryanto1 somehow it is still failing with circle ci, even after I merged your change. Would you mind sharing your insight on this?

**Comment by muryanto1** [comment]
@lee1043  sorry, this is due to 'validateNightlyNew' branch of cdat/cdat has been merged to 'master', and I deleted that branch. I neglected to give you a heads-up. 
See https://github.com/PCMDI/pcmdi_metrics/pull/639. once the build for that PR passes, please merge that branch.

**Comment by lee1043** [comment]
All test passed on circle ci except for linux_pmp_py2, linux_pmp_py3 and macos_pmp_py2, macos_pmp_py3. Following the comment of @muryanto1 at https://github.com/PCMDI/pcmdi_metrics/pull/639#issuecomment-656327238 I think it is okay to be merged now.

**Comment by lee1043** [comment]
@gleckler1 I am merging the MJO EWR to the master, could you please give a quick review and approve unless you see any problems? Thanks!

**Comment by lee1043** [comment]
This PR will resolve https://github.com/PCMDI/pcmdi_metrics/issues/589

**Pull request merged**
