### PR TITLE
added option for dry run

### LINKED ISSUE #320: external check of parameter table model and obs data
@doutriaux1 @durack1 With a switch available on the parameter table it would be great to be able to do a dry run only on trying to read all model (including land sea masks) and obs data and to report the results in a file that can be browsed.   If there is a single script for doing all of these checks CD, PG and PD via iteration should be able to provide some comprehensive error trapping.

### PR DESCRIPTION
**Pull request by doutriaux1**
which means no computations (just read in data)
fix #320

### CODE REVIEW

**Comment by doutriaux1** [comment]
@gleckler1 should be what you want.

**Comment by doutriaux1** [comment]
@gleckler1 is that what you wanted?

**Comment by gleckler1** [comment]
@doutriaux1 @durack1 its ok for now, so I'm ok to add it to master.   Later we'll want to improve on it  as it prints out stuff that does not relate to errors (e.g., "obs shape is") and at some point Paul can make it more of a log file.

**Comment by durack1** [comment]
@doutriaux1 is this good to go - tests are failing, does this also need master merged in?

**Comment by doutriaux1** [comment]
yp. I'm on it

**Comment by durack1** [comment]
@doutriaux1 is this dead - or does it need to be rebased?

**Comment by gleckler1** [comment]
@doutriaux1 maybe it has been replaced by the recently added '-t' option ?

**Comment by doutriaux1** [comment]
@durack1 let me update the branch.

**Comment by doutriaux1** [comment]
@durack1 at your convenience

**Comment by durack1** [comment]
Geez @doutriaux1 even `pep8'd`.. We might have to create that `Robust` label after all.. I'll wait for a green `travis` before merging, all looks good to me

**Pull request merged**
