### PR TITLE
677 pjg obsdic

### PR DESCRIPTION
**Pull request by gleckler1**

### CODE REVIEW

**Comment by gleckler1** [comment]
@acordonez @lee1043 I'm confused by the "conflicting file" above.   Why can't we just update/replace the version.py?  Any ideas?

**Comment by acordonez** [comment]
@gleckler1 Did version.py get updated in master since you created your branch? That might cause a conflict.

**Comment by gleckler1** [comment]
@acordonez  I'm not sure, and in any case don't understand the reasons or implications for doing this.  But I have cp version.py from master, pushed again, and am awaiting tests again.

**Comment by gleckler1** [comment]
@acordonez @lee1043  looks like this one is good to go...

**Review by lee1043 — APPROVED** [review]

**Pull request merged**
