### PR TITLE
Added rmsc_xyt.py and modified mean_climate_metrics_calculations.py

### PR DESCRIPTION
**Pull request by jservonnat**

### CODE REVIEW

**Comment by jservonnat** [comment]
...
I've merged my branch into PCMDI/master but this is an error. This should only have been a PR.
... thought I was merging it on my repo... didn't see the switch in repo.
This doesn't involve too many changes so I don't think it will be an issue. I will be more careful next time.

**Comment by durack1** [comment]
@jservonnat @gleckler1 I wonder if we should revert this merge? It seems that the travis testing didn't work, which probably has something to do with the test baselines not being updated, in addition to the [other problems that it seems travis was having](https://travis-ci.org/PCMDI/pcmdi_metrics/builds/206977469)

@zshaheen have you seen similar travis errors before? Any tips how to sort them?

**Comment by durack1** [comment]
Oh and @doutriaux1 is unlikely to be on much over the next couple of days, he's daddy daycare, along with being sick

**Comment by jservonnat** [comment]
@durack1 feel free to undo the merge (only 2 files modified), I can do that again later.

**Comment by zshaheen** [comment]
@durack1 @jservonnat Everyone's been having trouble with Travis CI for the past 2 days. I have a feeling this has to do with Amazon S3 being down. I just restart the build on Travis until it runs properly 😄

**Comment by gleckler1** [comment]
@zshaheen maybe this is why I can't get the nightly build to work?

**Comment by durack1** [comment]
@gleckler1 nope it was reverted.. https://github.com/PCMDI/pcmdi_metrics/pull/474

But not sure when it happened and if it got pulled into last nights master, and nightly-ed

**Pull request merged**
