### PR TITLE
627 ljw mov parallel

### PR DESCRIPTION
**Pull request by lee1043**
Resolve https://github.com/PCMDI/pcmdi_metrics/issues/627

### CODE REVIEW

**Comment by gleckler1** [comment]
@lee1043  Looks like some checks failed :-(

**Comment by lee1043** [comment]
@muryanto1 I think I have resolved all about flake8 related test failure, but the test is still failing and I don't have a clear idea, would you mind take a look? Thank you in advance.

**Comment by lee1043** [comment]
All test passed on circle ci except for linux_pmp_py2, linux_pmp_py3 and macos_pmp_py2, macos_pmp_py3. Following the comment of @muryanto1 at #639 (comment) I think it is okay to be merged now.

**Comment by gleckler1** [comment]
@lee1043 Why all the changes to diurnal on this branch?  I'm not sure this is correct as we have been using the diurnal branch heavily in master.

**Comment by lee1043** [comment]
@gleckler1 that is weird because I haven't touched anything from diurnal. Hmm.. let me check. Thanks for pointing it out!

**Comment by gleckler1** [comment]
@lee1043 when was the last time this was updated with master?   Maybe diurnal was changed after that?

**Comment by lee1043** [comment]
@gleckler1 yes, the change in diurnal was after my latest update with master (using the rebase functionality). I have tried rebase again with the latest current one but the rebase process was struggling to me.

**Comment by lee1043** [comment]
I am migrating necessary changes to a new branch that generated based on the current master and opened another PR https://github.com/PCMDI/pcmdi_metrics/pull/643. @gleckler1 I will let you know when the new PR is ready for reviewing.

**Pull request closed without merging**
