### PR TITLE
Demo 9b sea-ice data explore notebook update

### PR DESCRIPTION
**Pull request by lee1043**
- Added more data plot for visualizing time evolution
- Added table of contents to the notebook

### CODE REVIEW

**Review by durack1 — APPROVED** [review]
@lee1043 nice update - I particularly like that you have embedded section links in the table of contents, I hadn't figured out how to do that, but it's definitely useful. One addition could be to add a "table of contents" link at each section, so you can jump from halfway through to the top, and back down as you like, it's a looooong notebook (same with the demo when considering the output)

**Comment by durack1** [comment]
@lee1043 looks like this works for me https://nbviewer.org/github/PCMDI/pcmdi_metrics/blob/lee1043-patch-1/doc/jupyter/Demo/Demo_9b_seaIce_data_explore.ipynb#tmse. I presume this also works for the binder jupyterhub examples?

**Review by acordonez — APPROVED** [review]
I ran all cells in BinderHub. I also tried out all the links to make sure they work!

**Comment by lee1043** [comment]
@durack1 great suggestion. I added links to to top. This works best for nbviewer (I added that note in the notebook as well), but I am not sure for binder-hub. If you can give a try, let me know if that works. 

@acordonez thank you for checking the links. Can you help applying similar update to Demo9?

**Pull request merged**
