### PR TITLE
Mean climate 3d field vertical coordinate QC

### PR DESCRIPTION
**Pull request by lee1043**
Mean climate 3d field vertical coordinate QC
- pressure coordinate check
- unit check
- layer key check

### CODE REVIEW

**Comment by lee1043** [comment]
@acordonez when you get a chance, could you help checking if this PR makes any affect to the mean climate demo? No affect is expected but wanted to double check.

**Comment by acordonez** [comment]
@lee1043 Yes I'll test this out today

**Comment by acordonez** [comment]
@lee1043 The mean climate notebook 1b still runs with no errors. I did a before/after comparison for the Example 5 which uses zg_500 and am seeing some small (hundreths to thousandths place) differences in some of the metrics, for example rmsc_xy. It sounds like that is expected from this change?

**Comment by gleckler1** [comment]
@acordonez @lee1043 Acceptable discrepancies for zg I think.  You might compare with ta which in degrees C will be more intuitive.

**Comment by lee1043** [comment]
@acordonez thank you for checking this. @gleckler1 good point! I don't think we have obs for ta-850 in demo dataset, but I have compared to previously calculated from the PMP output database, and the difference is pretty subtle and I am confident on the consistency.

**Review by acordonez — APPROVED** [review]

**Pull request merged**
