### PR TITLE
Issue 459 json update json

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@durack1 @gleckler1 please review and approve.

**Comment by durack1** [comment]
@doutriaux1 only [4 tests seem to have run](https://travis-ci.org/PCMDI/pcmdi_metrics/builds/189605843#L790), we have more than that right?

**Comment by doutriaux1** [comment]
ooops.. I took them off for me locally... Putting them back on.

**Comment by doutriaux1** [comment]
@durack1 I think we're good now

**Comment by durack1** [comment]
@doutriaux1 13 tests, that is much better.. Almost a **robust** star..

**Pull request merged**
