### PR TITLE
Landsea mask generation: add PCMDI method as an option

### PR DESCRIPTION
**Pull request by lee1043**
The PCMDI method ([Taylor and Doutriaux, 2000](https://pcmdi.llnl.gov/report/ab58.html)) is added for land mask generation.

Usage:
```python
from pcmdi_metrics.utils import create_land_sea_mask

mask = create_land_sea_mask(ds, method="pcmdi")
```

### CODE REVIEW

**Comment by lee1043** [comment]
Jupyter notebook for testing (please uncompress once downloaded):
[test_landmask_generation.ipynb.zip](https://github.com/PCMDI/pcmdi_metrics/files/14429469/test_landmask_generation.ipynb.zip)

**Comment by lee1043** [comment]
@bosup would you be able to check if this work for you?

**Comment by lee1043** [comment]
The code is now ready for review.

**Review by bosup — APPROVED** [review]
looks good!

**Comment by lee1043** [comment]
@bosup thanks for reviewing!

**Pull request merged**
